[platformio]
default_envs = waveshare_esp32_s3_touch_lcd_3_5

[env:waveshare_esp32_s3_touch_lcd_3_5]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 460800
upload_port = COM4
monitor_port = COM4
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
lib_deps =
    moononournation/GFX Library for Arduino@1.5.5
    robtillaart/TCA9554@0.1.2

