// Production HTML + production C++ job engine. HTTP pairing is a test double;
// lease/takeover behavior is covered by native Control and physical two-browser tests.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process'),readline=require('node:readline'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=path.resolve(root,'../..',process.env.TOPORTK_TEST_RECORD||'tests/2026-09-10-survey-workflow');fs.mkdirSync(output,{recursive:true});
const html=fs.readFileSync(path.join(root,'src/survey_ui.h'),'utf8').split('R"SURVEY(')[1].split(')SURVEY"')[0];
const extras=fs.readFileSync(path.join(root,'src/survey_tools_ui.h'),'utf8').split('R"TOOLS(')[1].split(')TOOLS"')[0];
const fixture=JSON.parse(fs.readFileSync(path.join(root,'test/test_survey.cpp'),'utf8').split('fixture=R"(')[1].split(')";')[0]);
const engine=spawn(path.join(root,'.pio/test_survey.exe'),['--serve'],{cwd:root,stdio:['pipe','pipe','inherit']});let waiting=[],chain=Promise.resolve(),offline=false,controller=false,leaseToken='',claims=0;
readline.createInterface({input:engine.stdout}).on('line',line=>waiting.shift()?.(JSON.parse(line)));
function rpc(data){const request=chain.then(()=>new Promise(resolve=>{waiting.push(resolve);engine.stdin.write(JSON.stringify(data)+'\n')}));chain=request;return request}
const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.url==='/survey'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(html)}res.setHeader('Content-Type','application/json');let raw='';for await(const chunk of req)raw+=chunk;const body=raw?JSON.parse(raw):{};if(offline){res.statusCode=503;return res.end('{"error":"offline"}')}
if(req.url==='/survey-tools.js'){res.setHeader('Content-Type','application/javascript; charset=utf-8');return res.end(extras)}
if(req.url.startsWith('/api/v1/data?')){const query=Object.fromEntries(new URL(req.url,'http://localhost').searchParams);for(const key of ['offset','at'])if(key in query)query[key]=Number(query[key]);if('deleted'in query)query.deleted=query.deleted==='true';return res.end(JSON.stringify(await rpc({query})))}
if(req.url==='/api/v1/control'){const base=(await rpc({})).role==='BASE';const accepted=/^[0-9a-f]{32}$/.test(body.client||'')&&(!base||body.pin==='123456');if(accepted){controller=true;leaseToken='fixture-token-'+(++claims)}res.statusCode=accepted?200:403;return res.end(JSON.stringify(accepted?{token:leaseToken}:{error:'pairing_failed'}))}
if(req.url==='/api/v1/control/release'){if(req.headers.authorization==='Bearer '+leaseToken)controller=false;return res.end('{}')}
if(req.url==='/api/v1/command'){if(!controller||req.headers.authorization!=='Bearer '+leaseToken){res.statusCode=401;return res.end('{"error":"claim_control_first"}')} await rpc({command:body});res.statusCode=202;return res.end('{"state":"queued"}')}
if(req.url==='/api/v1/survey'){res.setHeader('X-Controller',String(controller&&req.headers.authorization==='Bearer '+leaseToken));return res.end(JSON.stringify(await rpc({})))}res.statusCode=404;res.end('{}')});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/survey`,browser=await chromium.launch({channel:'msedge',headless:true});const errors=[];try{
const page=await browser.newPage({viewport:{width:390,height:844}});page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>document.querySelector('#connection').textContent.startsWith('Live'));assert(await page.locator('#create button').isDisabled());await page.locator('#pairPanel summary').click();assert(await page.locator('#controlPinLabel').isHidden());await page.locator('#pair button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#controlState').textContent==='You control this instrument');
// Another browser takes control; the old bearer cannot write or release the new lease.
const oldToken=await page.evaluate(()=>sessionStorage.getItem('surveyToken'));
const secondContext=await browser.newContext(),second=await secondContext.newPage();await second.goto(url);await second.waitForFunction(()=>!document.querySelector('#takeControl').disabled);await second.locator('#pairPanel summary').click();await second.locator('#takeControl').click();await second.waitForFunction(()=>document.querySelector('#controlState').textContent==='You control this instrument');await page.waitForFunction(()=>document.querySelector('#controlState').textContent==='View only · Take control');assert(await page.locator('#create button').isDisabled());
const rejected=await page.request.post(url.replace('/survey','/api/v1/command'),{headers:{Authorization:'Bearer '+oldToken},data:{id:'a'.repeat(32),op:'invalid_test_only'}});assert.equal(rejected.status(),401);
await page.request.post(url.replace('/survey','/api/v1/control/release'),{headers:{Authorization:'Bearer '+oldToken},data:{}});await second.reload();await second.waitForFunction(()=>document.querySelector('#controlState').textContent==='You control this instrument');
await page.locator('#pairPanel').evaluate(x=>x.open=true);await page.locator('#takeControl').click();await page.waitForFunction(()=>document.querySelector('#controlState').textContent==='You control this instrument');await second.waitForFunction(()=>document.querySelector('#controlState').textContent==='View only · Take control');await secondContext.close();
await page.locator('#create input').fill('Browser field fixture');await page.locator('#create button').click();await page.waitForFunction(()=>document.querySelector('#setupTitle').textContent.includes('Browser field fixture'));
assert.equal(await page.locator('[name=zone]').inputValue(),'13');assert.equal(await page.locator('[name=south]').inputValue(),'false');assert.equal(await page.locator('[name=units]').inputValue(),'m');assert.equal(await page.locator('[name=vertical]').inputValue(),'ellipsoid');assert.equal(await page.locator('[name=rover_model]').inputValue(),'GNSS HA-609');assert.equal(await page.locator('[name=base_mode]').inputValue(),'temporary');assert(await page.locator('#start').isDisabled());
// Collapsed required fields must reveal themselves on native validation.
await page.locator('#config button').click();assert(await page.locator('.setup-group').nth(1).evaluate(x=>x.open));
await page.locator('.setup-group').evaluateAll(rows=>rows.forEach(x=>x.open=true));
for(const [name,value]of Object.entries(fixture)){const field=page.locator(`#config [name="${name}"]`);const tag=await field.evaluate(x=>x.tagName);if(typeof value==='boolean'){if(tag==='SELECT')await field.selectOption(String(value));else await field.setChecked(value)}else if(tag==='SELECT')await field.selectOption(String(value));else await field.fill(String(value))}
await page.locator('#reviewConfig').check();assert(await page.locator('#config').evaluate(x=>x.checkValidity()));
for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,`setup-${width}.png`),fullPage:true})}
await page.locator('#config button').click();await page.waitForFunction(()=>!document.querySelector('[data-panel=collect]').hidden&&!document.querySelector('#start').disabled);await page.locator('#collect [name=point_id]').fill('1001');await page.locator('#collect [name=code]').fill('BM');await page.locator('.description-fold').evaluate(x=>x.open=true);await page.locator('#collect [name=description]').fill('Browser integration fixture');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({advance:1000});await rpc({advance:1000});await page.waitForFunction(()=>!document.querySelector('#lastPoint').hidden);assert.match(await page.locator('#pointDetails').textContent(),/Ground height 2202.000 m/);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'point-phone.png'),fullPage:true});await rpc({restart:true});await page.reload();await page.waitForFunction(()=>document.querySelector('#instrument').textContent.includes('Browser field fixture'));await page.locator('[data-tab=collect]').click();assert.match(await page.locator('#pointDetails').textContent(),/1001/);
await page.locator('[data-tab=points]').click();await page.locator('#downloadsPanel,#targetsPanel,#linesPanel').evaluateAll(rows=>rows.forEach(x=>x.open=true));await page.waitForFunction(()=>document.querySelector('#pointsStatus').textContent.includes('1 shown'));await page.locator('#pointsList button').first().click();await page.waitForFunction(()=>!document.querySelector('#pointInspector').hidden);assert.match(await page.locator('#pointRaw').textContent(),/receiver_ellipsoidal_h_m/);await page.locator('#pointEdit [name=code]').fill('BM-EDIT');await page.locator('#pointEdit [name=note]').fill('Independent review');await page.locator('#pointEdit [name=description]').fill('=1+1, \"survey note\"');await page.locator('#pointEdit [name=reason]').fill('Review test');await page.locator('#pointEdit button').click();await page.waitForFunction(()=>document.querySelector('#pointsList').textContent.includes('BM-EDIT'));await page.locator('#pointsList button').first().click();await page.waitForFunction(()=>document.querySelector('#pointRecord').textContent.includes('Metadata revision 2'));await page.locator('#pointEdit [name=deleted]').check();await page.locator('#pointEdit [name=reason]').fill('Deletion test');await page.locator('#pointEdit button').click();await page.waitForFunction(()=>document.querySelector('#pointsStatus').textContent.startsWith('0 shown'));await page.locator('#showDeleted').check();await page.locator('#pointsList button').first().click();await page.waitForFunction(()=>document.querySelector('#pointRecord').textContent.includes('Metadata revision 3'));await page.locator('#pointEdit [name=deleted]').uncheck();await page.locator('#pointEdit [name=reason]').fill('Restore test');await page.locator('#pointEdit button').click();await page.waitForFunction(()=>!document.querySelector('#pointsList').textContent.includes('DELETED'));
const backupDownload=page.waitForEvent('download');await page.locator('#exportBackup').click();const backup=await backupDownload;await backup.saveAs(path.join(output,'fixture-backup.json'));const exported=JSON.parse(fs.readFileSync(path.join(output,'fixture-backup.json'),'utf8'));assert.equal(exported.records.length,7);assert.equal(exported.records.filter(x=>JSON.parse(x.json).op==='point.edit').length,3);
const csvDownload=page.waitForEvent('download');await page.locator('#exportCSV').click();const csv=await csvDownload;await csv.saveAs(path.join(output,'fixture-points.csv'));assert.match(fs.readFileSync(path.join(output,'fixture-points.csv'),'utf8'),/observation_json/);await page.waitForFunction(()=>document.querySelector('#exportStatus').textContent.startsWith('CSV downloaded'));
await page.screenshot({path:path.join(output,'point-review-phone.png'),fullPage:true});await page.locator('[data-tab=collect]').click();
// Manual references are persisted separately from measured observations.
await page.locator('[data-tab=points]').click();await page.locator('#downloadsPanel,#targetsPanel,#linesPanel').evaluateAll(rows=>rows.forEach(x=>x.open=true));await page.locator('#targetForm').locator('..').locator('summary').click();
for(const [name,value] of Object.entries({id:'CP1',easting:489489.918,northing:2145101.646,height:2202,source:'Independent browser test control'}))await page.locator(`#targetForm [name="${name}"]`).fill(String(value));
await page.locator('#targetForm [name=reference_confirmed]').check();await page.locator('#targetForm [name=independent_source]').check();await page.locator('#targetForm button').click();await page.waitForFunction(()=>document.querySelector('#targetsList').textContent.includes('CP1'));assert.match(await page.locator('#targetsList').textContent(),/Independent browser test control/);await rpc({restart:true});await page.reload();await page.waitForFunction(()=>document.querySelector('#connection').textContent.startsWith('Live'));await page.locator('[data-tab=points]').click();await page.locator('#downloadsPanel,#targetsPanel,#linesPanel').evaluateAll(rows=>rows.forEach(x=>x.open=true));await page.waitForFunction(()=>document.querySelector('#targetsList').textContent.includes('CP1'));await page.screenshot({path:path.join(output,'targets-phone.png'),fullPage:true});await page.locator('[data-tab=collect]').click();
// Check and repeat are distinct quality-gated occupations with frozen references.
await page.locator('#occupationPurpose').selectOption('check');await page.waitForFunction(()=>document.querySelector('#checkTarget').options.length>1);await page.locator('#checkTarget').selectOption('CP1');await page.locator('#checkH').fill('0.03');await page.locator('#checkV').fill('0.05');await page.locator('#collect [name=point_id]').fill('CHECK-START');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({advance:1000});await rpc({advance:1000});await page.waitForFunction(()=>document.querySelector('#comparisonResult').textContent.includes('CONTROL CHECK'));assert.match(await page.locator('#comparisonResult').textContent(),/WITHIN TOLERANCE/);await page.screenshot({path:path.join(output,'check-phone.png'),fullPage:true});
await page.locator('#occupationPurpose').selectOption('repeat');await page.waitForFunction(()=>Array.from(document.querySelector('#repeatPoint').options).some(x=>x.value==='1001'));await page.locator('#repeatPoint').selectOption('1001');await page.locator('#checkPhase').selectOption('end');await page.locator('#collect [name=point_id]').fill('REPEAT-END');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({advance:1000});await rpc({advance:1000});await page.waitForFunction(()=>document.querySelector('#comparisonResult').textContent.includes('REPEATABILITY'));await page.locator('#occupationPurpose').selectOption('stake');await page.locator('#checkTarget').selectOption('CP1');await page.waitForFunction(()=>document.querySelector('#stakeGuidance').textContent.includes('Grid distance'));offline=true;await page.waitForFunction(()=>document.querySelector('#stakeGuidance').textContent.includes('unavailable'));offline=false;await page.waitForFunction(()=>document.querySelector('#stakeGuidance').textContent.includes('Grid distance'));await page.locator('#collect [name=point_id]').fill('AS-STAKED');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({advance:1000});await rpc({advance:1000});await page.waitForFunction(()=>document.querySelector('#comparisonResult').textContent.includes('AS-STAKED'));await page.screenshot({path:path.join(output,'stakeout-phone.png'),fullPage:true});await page.locator('#occupationPurpose').selectOption('topo');await page.locator('[data-tab=points]').click();await page.locator('#downloadsPanel,#targetsPanel,#linesPanel').evaluateAll(rows=>rows.forEach(x=>x.open=true));const checkDownload=page.waitForEvent('download');await page.locator('#exportCSV').click();await (await checkDownload).saveAs(path.join(output,'fixture-checks.csv'));await page.locator('[data-tab=collect]').click();
// Continuous quality loss must abort without replacing the last committed point.
await page.locator('#collect [name=point_id]').fill('1002');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({fix:{fixed:false},advance:1000});await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('RTK FIXED'));assert.match(await page.locator('#pointDetails').textContent(),/^AS-STAKED/);
// Manual line vertices stay separate observations with explicit topology and breaks.
await rpc({fix:{fixed:true}});await page.waitForFunction(()=>!document.querySelector('#start').disabled);await page.locator('#lineOptions summary').click();
async function vertex(point){await page.locator('#collect [name=point_id]').fill(point);await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({advance:1000});await rpc({advance:1000});await page.waitForFunction(id=>document.querySelector('#pointDetails').textContent.startsWith(id),point)}
await page.locator('#lineAction').selectOption('start');await page.locator('#newLineId').fill('LINE1');await page.locator('#collect [name=code]').fill('EDGE');await vertex('LV1');await page.waitForFunction(()=>Array.from(document.querySelector('#openLine').options).some(x=>x.value==='LINE1'));await page.locator('#lineAction').selectOption('continue');await page.locator('#openLine').selectOption('LINE1');await vertex('LV2');await page.waitForFunction(()=>document.querySelector('#lineSelection').textContent.includes('previous vertex LV2'));await page.locator('#lineAction').selectOption('end');await vertex('LV3');await page.waitForFunction(()=>document.querySelector('#linesList').textContent.includes('CLOSED'));await page.screenshot({path:path.join(output,'line-collect-phone.png'),fullPage:true});
await page.locator('#lineAction').selectOption('start');await page.locator('#newLineId').fill('GAP');await vertex('LV4');await page.waitForFunction(()=>Array.from(document.querySelector('#openLine').options).some(x=>x.value==='GAP'));await page.locator('#lineAction').selectOption('continue');await page.locator('#openLine').selectOption('GAP');await page.locator('#collect [name=point_id]').fill('LV5');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({fix:{fixed:false},advance:1000});await page.waitForFunction(()=>document.querySelector('#linesList').textContent.includes('BROKEN'));await rpc({fix:{fixed:true}});await page.locator('#lineAction').selectOption('none');
await page.locator('[data-tab=points]').click();await page.locator('#downloadsPanel,#targetsPanel,#linesPanel').evaluateAll(rows=>rows.forEach(x=>x.open=true));await page.locator('#pointsList .job').filter({hasText:'LV2'}).locator('button').click();await page.waitForFunction(()=>document.querySelector('#pointHeading').textContent==='Point LV2');await page.locator('#pointEdit [name=deleted]').check();await page.locator('#pointEdit [name=reason]').fill('Vertex deletion test');await page.locator('#pointEdit button').click();await page.waitForFunction(()=>document.querySelector('#linesList').textContent.includes('LINE1 · BROKEN'));await page.waitForFunction(()=>document.querySelector('#pointRecord').textContent.includes('Metadata revision 2'));await page.locator('#pointEdit [name=deleted]').uncheck();await page.locator('#pointEdit [name=reason]').fill('Restore without reconnecting');await page.locator('#pointEdit button').click();await page.waitForFunction(()=>document.querySelector('#pointRecord').textContent.includes('Metadata revision 3'));await rpc({restart:true});await page.reload();await page.waitForFunction(()=>document.querySelector('#connection').textContent.startsWith('Live'));await page.locator('[data-tab=points]').click();await page.locator('#downloadsPanel,#targetsPanel,#linesPanel').evaluateAll(rows=>rows.forEach(x=>x.open=true));await page.waitForFunction(()=>document.querySelector('#linesList').textContent.includes('LINE1 · BROKEN'));await page.screenshot({path:path.join(output,'lines-phone.png'),fullPage:true});
const linesCSV=page.waitForEvent('download');await page.locator('#exportCSV').click();await (await linesCSV).saveAs(path.join(output,'fixture-lines.csv'));const linesBackup=page.waitForEvent('download');await page.locator('#exportBackup').click();await (await linesBackup).saveAs(path.join(output,'fixture-lines-backup.json'));
// Editing survives polling; disconnect locks all mutators.
await page.locator('[data-tab=setup]').click();await page.locator('.setup-group').evaluateAll(rows=>rows.forEach(x=>x.open=true));await page.locator('#config [name=base_lat]').fill('19.8');await page.waitForTimeout(1200);assert.equal(await page.locator('#config [name=base_lat]').inputValue(),'19.8');offline=true;await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('unavailable'));assert(await page.locator('#config button').isDisabled());assert.equal(await page.locator('#config [name=base_lat]').inputValue(),'19.8');offline=false;await page.waitForFunction(()=>document.querySelector('#connection').textContent.startsWith('Live'));
// An in-flight detail response must not populate a different active job.
await page.locator('[data-tab=points]').click();await page.locator('#downloadsPanel,#targetsPanel,#linesPanel').evaluateAll(rows=>rows.forEach(x=>x.open=true));await page.waitForFunction(()=>document.querySelector('#pointsList button'));
let releaseDetail,detailStarted;const held=new Promise(r=>releaseDetail=r),started=new Promise(r=>detailStarted=r);
await page.route('**/api/v1/data?view=point&**',async route=>{const response=await route.fetch();detailStarted();await held;await route.fulfill({response})});
await page.locator('#pointsList button').first().click();await started;await rpc({command:{id:'ffffffffffffffffffffffffffffff01',op:'job.create',name:'Separate job'}});await page.waitForFunction(()=>document.querySelector('#instrument').textContent.includes('Separate job'));releaseDetail();await page.waitForTimeout(300);assert(await page.locator('#pointInspector').isHidden());await page.unroute('**/api/v1/data?view=point&**');
await rpc({fix:{rover:false}});await page.waitForFunction(()=>!document.querySelector('[data-panel=base]').hidden);await page.screenshot({path:path.join(output,'base-phone.png'),fullPage:true});assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: production browser/C++ engine create-configure-collect-restart, quality abort, edit preservation, offline locks, Base view, 390/768/1280 layouts and no JS errors');
}finally{await browser.close();server.close();engine.kill()}})().catch(e=>{console.error(e);engine.kill();server.close();process.exitCode=1});
