// Production HTML + production C++ job engine. HTTP pairing is a test double;
// lease/rate-limit behavior is covered by the native Control tests.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process'),readline=require('node:readline'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=path.resolve(root,'../../tests/2026-09-10-survey-workflow');fs.mkdirSync(output,{recursive:true});
const html=fs.readFileSync(path.join(root,'src/survey_ui.h'),'utf8').split('R"SURVEY(')[1].split(')SURVEY"')[0];
const fixture=JSON.parse(fs.readFileSync(path.join(root,'test/test_survey.cpp'),'utf8').split('fixture=R"(')[1].split(')";')[0]);
const engine=spawn(path.join(root,'.pio/test_survey.exe'),['--serve'],{cwd:root,stdio:['pipe','pipe','inherit']});let waiting=[],chain=Promise.resolve(),offline=false,controller=false;
readline.createInterface({input:engine.stdout}).on('line',line=>waiting.shift()?.(JSON.parse(line)));
function rpc(data){const request=chain.then(()=>new Promise(resolve=>{waiting.push(resolve);engine.stdin.write(JSON.stringify(data)+'\n')}));chain=request;return request}
const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.url==='/survey'){res.setHeader('Content-Type','text/html');return res.end(html)}res.setHeader('Content-Type','application/json');let raw='';for await(const chunk of req)raw+=chunk;const body=raw?JSON.parse(raw):{};if(offline){res.statusCode=503;return res.end('{"error":"offline"}')}
if(req.url==='/api/v1/control'){controller=body.pin==='123456';res.statusCode=controller?200:403;return res.end(JSON.stringify(controller?{token:'fixture-token'}:{error:'pairing_failed'}))}
if(req.url==='/api/v1/control/release'){controller=false;return res.end('{}')}
if(req.url==='/api/v1/command'){assert.equal(req.headers.authorization,'Bearer fixture-token');assert(controller);await rpc({command:body});res.statusCode=202;return res.end('{"state":"queued"}')}
if(req.url==='/api/v1/survey'){res.setHeader('X-Controller',String(controller&&req.headers.authorization==='Bearer fixture-token'));return res.end(JSON.stringify(await rpc({})))}res.statusCode=404;res.end('{}')});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/survey`,browser=await chromium.launch({channel:'msedge',headless:true});const errors=[];try{
const page=await browser.newPage({viewport:{width:390,height:844}});page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>document.querySelector('#connection').textContent.startsWith('Live'));assert(await page.locator('#create button').isDisabled());await page.locator('#pairPanel summary').click();await page.locator('#pair input').fill('123456');await page.locator('#pair button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#controlState').textContent==='You control this instrument');
await page.locator('#create input').fill('Browser field fixture');await page.locator('#create button').click();await page.waitForFunction(()=>document.querySelector('#setupTitle').textContent.includes('Browser field fixture'));
assert.equal(await page.locator('[name=zone]').inputValue(),'13');assert.equal(await page.locator('[name=south]').inputValue(),'false');assert.equal(await page.locator('[name=units]').inputValue(),'m');assert.equal(await page.locator('[name=vertical]').inputValue(),'ellipsoid');assert.equal(await page.locator('[name=rover_model]').inputValue(),'GNSS HA-609');assert.equal(await page.locator('[name=base_mode]').inputValue(),'temporary');assert(await page.locator('#start').isDisabled());
for(const [name,value]of Object.entries(fixture)){const field=page.locator(`#config [name="${name}"]`);const tag=await field.evaluate(x=>x.tagName);if(typeof value==='boolean'){if(tag==='SELECT')await field.selectOption(String(value));else await field.setChecked(value)}else if(tag==='SELECT')await field.selectOption(String(value));else await field.fill(String(value))}
await page.locator('#reviewConfig').check();assert(await page.locator('#config').evaluate(x=>x.checkValidity()));
for(const width of [390,768,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,`setup-${width}.png`),fullPage:true})}
await page.locator('#config button').click();await page.waitForFunction(()=>!document.querySelector('[data-panel=collect]').hidden&&!document.querySelector('#start').disabled);await page.locator('#collect [name=point_id]').fill('1001');await page.locator('#collect [name=code]').fill('BM');await page.locator('#collect [name=description]').fill('Browser integration fixture');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({advance:1000});await rpc({advance:1000});await page.waitForFunction(()=>!document.querySelector('#lastPoint').hidden);assert.match(await page.locator('#pointDetails').textContent(),/Ground height 2202.000 m/);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'point-phone.png'),fullPage:true});await rpc({restart:true});await page.reload();await page.waitForFunction(()=>document.querySelector('#instrument').textContent.includes('Browser field fixture'));await page.locator('[data-tab=collect]').click();assert.match(await page.locator('#pointDetails').textContent(),/1001/);
// Continuous quality loss must abort without replacing the last committed point.
await page.locator('#collect [name=point_id]').fill('1002');await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('epochs'));await rpc({fix:{fixed:false},advance:1000});await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('RTK FIXED'));assert.match(await page.locator('#pointDetails').textContent(),/^1001/);
// Editing survives polling; disconnect locks all mutators.
await page.locator('[data-tab=setup]').click();await page.locator('#config [name=base_lat]').fill('19.8');await page.waitForTimeout(1200);assert.equal(await page.locator('#config [name=base_lat]').inputValue(),'19.8');offline=true;await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('unavailable'));assert(await page.locator('#config button').isDisabled());assert.equal(await page.locator('#config [name=base_lat]').inputValue(),'19.8');offline=false;await page.waitForFunction(()=>document.querySelector('#connection').textContent.startsWith('Live'));
await rpc({fix:{rover:false}});await page.waitForFunction(()=>!document.querySelector('[data-panel=base]').hidden);await page.screenshot({path:path.join(output,'base-phone.png'),fullPage:true});assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: production browser/C++ engine create-configure-collect-restart, quality abort, edit preservation, offline locks, Base view, 390/768/1280 layouts and no JS errors');
}finally{await browser.close();server.close();engine.kill()}})().catch(e=>{console.error(e);engine.kill();server.close();process.exitCode=1});
