// Production UI with read-only sample data; no physical commands.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=path.resolve(root,'../..',process.env.TOPORTK_TEST_RECORD||'tests/2026-09-11-gui-redesign');
const html=fs.readFileSync(path.join(root,'src/survey_ui.h'),'utf8').split('R"SURVEY(')[1].split(')SURVEY"')[0];
const js=fs.readFileSync(path.join(root,'src/survey_tools_ui.h'),'utf8').split('R"TOOLS(')[1].split(')TOOLS"')[0];
const state=JSON.parse(fs.readFileSync(path.resolve(root,'../../tests/2026-09-11-manual-lines/hardware-final.json'))).A;
state.unit='Preview';state.jobs=[{id:'sample',name:'North field',revision:0,points:0}];state.active_job='sample';state.operation={id:'',state:'idle',message:''};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{const url=route.request().url();assert.equal(route.request().method(),'GET');if(url.endsWith('/survey-tools.js'))return route.fulfill({body:js,contentType:'application/javascript'});if(url.endsWith('/api/v1/survey'))return route.fulfill({json:state});if(url.includes('/api/v1/data?'))return route.fulfill({json:{at:2,total:0,points:[],targets:[],lines:[]}});return route.fulfill({body:html,contentType:'text/html'})});
await page.goto('http://layout.test/survey');await page.waitForFunction(()=>document.querySelector('#connection').textContent.startsWith('Live'));
assert.equal(await page.locator('.setup-group').count(),4);assert(await page.locator('#downloadsPanel,#targetsPanel,#linesPanel').evaluateAll(rows=>rows.every(x=>!x.open)));
for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});for(const tab of ['jobs','setup','collect','points']){await page.locator(`[data-tab=${tab}]`).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${tab} overflow at ${width}`);await page.locator(`[data-tab=${tab}]`).hover();await page.waitForTimeout(180);assert.equal(await page.locator(`[data-tab=${tab}]`).evaluate(x=>getComputedStyle(x).backgroundColor),'rgb(23, 60, 80)');await page.screenshot({path:path.join(output,`layout-${tab}-${width}.png`),fullPage:true});if(width<700){const box=await page.locator('nav').boundingBox();assert(box.y>=0&&box.y+box.height<=901);}}}
await page.setViewportSize({width:390,height:844});await page.addStyleTag({content:':root{font-size:32px}'});for(const tab of ['jobs','setup','collect','points']){await page.locator(`[data-tab=${tab}]`).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${tab} overflow with 200% text`)}
await page.keyboard.press('Tab');await page.locator('[data-tab=jobs]').focus();assert(await page.locator('[data-tab=jobs]').evaluate(x=>x.matches(':focus-visible')));assert(await page.locator('#start').isDisabled());assert.deepEqual(errors,[]);
fs.writeFileSync(path.join(output,'layout-results.json'),JSON.stringify({result:'PASS',checks:['320/390/768/1280 px all survey screens','390 px with 200% text','collapsed secondary panels','four setup groups','visible phone navigation','keyboard focus','read-only locking','no JavaScript errors']},null,2));console.log('PASS: responsive survey layout, 200% text, focus and disclosure defaults');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
