#include "survey_engine.h"
#include "survey_store.h"
#include "survey_control.h"
#include <cassert>
#include <iostream>
#include <map>
#include <fstream>
#include <cstring>
using namespace survey;
struct MemoryStore:Store {
  std::map<unsigned,std::string> records;bool ready=true,fail=false,uncertain=false;
  bool initialize() override{return ready;}
  bool read(unsigned n,std::string &s,bool &exists) override {exists=records.count(n);if(exists)s=records[n];return exists||records.empty()||n>records.rbegin()->first;}
  bool commit(unsigned n,const std::string &s) override {if(fail||records.count(n))return false;records[n]=s;return !uncertain;}
};
struct ReceiverMock:Receiver {bool available=true;unsigned calls=0;BaseRequest last;bool apply(const BaseRequest &r) override {++calls;last=r;return available;}};
std::string id(unsigned n){char out[33];std::snprintf(out,sizeof(out),"%032x",n);return out;}
std::string encode(JsonDocument &d){std::string s;serializeJson(d,s);return s;}
DynamicJsonDocument decode(const std::string &s){DynamicJsonDocument d(32768);assert(!deserializeJson(d,s));return d;}
const char *fixture=R"({"crs":"wgs84_utm","frame":"WGS84","epoch":2026.7,"reference_confirmed":true,"zone":14,"south":false,"units":"m","vertical":"ellipsoid","rover_model":"Test reference","rover_height":2,"rover_offset":0,"rover_radius":0,"rover_method":"vertical","base_model":"Test reference","base_height":1.5,"base_offset":0,"base_radius":0,"base_method":"vertical","antenna_confirmed":true,"base_name":"Test control","station":7,"base_mode":"known","base_lat":19.4,"base_lon":-99.1,"base_ground_h":2200,"base_tolerance":0.02,"duration":2,"min_samples":3,"h_limit":0.03,"v_limit":0.05,"correction_limit":3000})";
struct Rig {
  MemoryStore store;ReceiverMock receiver;Engine engine;Fix fix;unsigned next=10;std::string job=id(1);
  Rig():engine(store,receiver){fix.now=fix.received=10000;fix.epoch=1473000000000ULL;fix.rover=fix.profile_ok=fix.position_valid=fix.fixed=fix.linked=fix.reference_valid=true;fix.position={19.4001,-99.1001,2204};fix.reference=ecef({19.4,-99.1,2201.5});fix.station=7;fix.hacc=.01;fix.vacc=.02;fix.satellites=30;std::strcpy(fix.utc,"2026-09-10T12:00:00Z");engine.recover();}
  DynamicJsonDocument state(){return decode(engine.snapshot(fix));}
  std::string command(const char *op,unsigned n=0){DynamicJsonDocument d(16384);d["id"]=id(n?n:next++);d["op"]=op;d["job"]=job;d["revision"]=1;d["name"]="Bench fixture";d["point_id"]="1001";d["code"]="BM";d["description"]="Test observation";d["confirm"]=true;return encode(d);}
  void send(const std::string &s){engine.command(s.c_str(),fix);}
  void setup(){send(command("job.create",1));auto d=decode(command("job.configure",2));d["revision"]=0;auto c=decode(fixture);d["config"]=c.as<JsonVariantConst>();send(encode(d));assert(state()["jobs"][0]["revision"]==1);}
  void advance(unsigned ms=1000){fix.now+=ms;fix.received=fix.now;fix.epoch+=ms;engine.tick(fix);}
};
void tests(const std::string &root){
  {Control c;char token[33];assert(c.claim("",id(1).c_str(),id(2).c_str(),1,token,33)==400);c.reset("123456");for(int i=0;i<5;++i)assert(c.claim("000000",id(1).c_str(),id(2).c_str(),100+i,token,33)==403);assert(c.claim("123456",id(1).c_str(),id(2).c_str(),200,token,33)==429);assert(c.claim("123456",id(1).c_str(),id(2).c_str(),60100,token,33)==200);assert(c.authorized(token,60100,false));assert(c.claim("123456",id(3).c_str(),id(4).c_str(),60200,token,33)==409);assert(!c.authorized(id(4).c_str(),60300,true));assert(c.authorized(id(2).c_str(),100000,true));assert(c.authorized(id(2).c_str(),219999,false));assert(!c.authorized(id(2).c_str(),220000,false));assert(c.claim("123456",id(3).c_str(),id(4).c_str(),220001,token,33)==200);c.release(token,220002);assert(!c.authorized(token,220003,false));c.reset("654321");assert(c.claim("123456",id(3).c_str(),id(4).c_str(),220004,token,33)==403);}
  {Rig r;r.setup();const auto c=r.command("collect.start");r.send(c);assert(r.state()["collection"]["samples"]==1);r.engine.tick(r.fix);assert(r.state()["collection"]["samples"]==1);r.advance();r.advance();auto s=r.state();assert(s["jobs"][0]["points"]==1);assert(std::abs(s["last_point"]["ground_ellipsoidal_h_m"].as<double>()-2202)<1e-6);assert(s["last_point"]["base_control_verified"]==true);assert(s["last_point"]["configuration_revision"]==1);const auto count=r.store.records.size();r.send(c);assert(r.store.records.size()==count);r.engine.recover();r.send(c);assert(r.state()["operation"]["state"]=="completed");assert(r.state()["jobs"][0]["points"]==1);r.send(r.command("collect.start"));assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();auto c=r.command("collect.start");r.send(c);r.engine.recover();r.send(c);assert(r.state()["operation"]["state"]=="interrupted");assert(r.state()["jobs"][0]["points"]==0);}
  for(int failure=0;failure<10;++failure){Rig r;r.setup();r.send(r.command("collect.start"));switch(failure){case 0:r.fix.fixed=false;break;case 1:r.fix.hacc=.04;break;case 2:r.fix.vacc=.06;break;case 3:r.fix.correction_age=3001;break;case 4:r.fix.station=8;break;case 5:r.fix.reference.x+=.01;break;case 6:r.fix.profile_ok=false;break;case 7:r.fix.position_valid=false;break;case 8:r.fix.now+=1501;break;case 9:r.fix.epoch-=1000;break;}r.engine.tick(r.fix);assert(r.state()["collection"]["active"]==false);assert(r.state()["jobs"][0]["points"]==0);assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();r.send(r.command("collect.start"));r.send(r.command("storage.recover"));assert(r.state()["collection"]["active"]==true);auto cancel=r.command("collect.cancel");r.send(cancel);auto count=r.store.records.size();r.engine.recover();r.send(cancel);assert(r.state()["operation"]["state"]=="completed"&&r.store.records.size()==count);}
  {Rig r;auto c=r.command("job.create",1);r.store.uncertain=true;r.send(c);assert(!r.state()["storage_ready"].as<bool>());r.store.uncertain=false;r.engine.recover();r.send(c);assert(r.state()["jobs"].size()==1);assert(r.state()["operation"]["state"]=="completed");auto other=decode(c);other["name"]="Changed";r.send(encode(other));assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();r.send(r.command("collect.start"));r.advance();r.store.fail=true;r.advance();assert(r.state()["jobs"][0]["points"]==0);assert(r.state()["operation"]["state"]=="rejected");r.store.fail=false;r.engine.recover();assert(r.state()["jobs"][0]["points"]==0);}
  {Rig r;r.store.ready=false;r.engine.recover();r.send(r.command("job.create"));assert(r.store.records.empty());}
  {Rig r;r.setup();auto d=decode(r.command("job.configure"));d["revision"]=0;d["config"]=decode(fixture).as<JsonVariantConst>();r.send(encode(d));assert(r.state()["operation"]["state"]=="rejected");d["revision"]=1;d["config"]["south"]=nullptr;r.send(encode(d));assert(r.state()["operation"]["state"]=="rejected");d["config"]["south"]=false;d["config"]["rover_method"]="slant";d["config"]["rover_radius"]=1;d["config"]["rover_height"]=.5;r.send(encode(d));assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();auto d=decode(r.command("job.configure"));d["config"]=decode(fixture).as<JsonVariantConst>();auto c=d["config"];c["base_mode"]="temporary";c["temporary_confirmed"]=true;c["rover_method"]="slant";c["rover_height"]=2.5;c["rover_radius"]=.7;c["rover_offset"]=.1;c["units"]="ft";c["vertical"]="constant_geoid";c["geoid_name"]="Bench local model";c["geoid_n"]=-30;c["geoid_lat"]=19.4;c["geoid_lon"]=-99.1;c["geoid_radius"]=100;r.send(encode(d));assert(r.state()["jobs"][0]["revision"]==2);auto collect=decode(r.command("collect.start"));collect["revision"]=2;r.send(encode(collect));r.advance();r.advance();auto p=r.state()["last_point"].as<JsonObjectConst>();auto s=r.state();assert(s["last_point"]["base_control_verified"]==false);assert(std::abs(s["last_point"]["height"].as<double>()-(2204-2.5+30)/.3048)<1e-5);r.fix.position.latitude+=.1;assert(r.state()["block_reason"].as<std::string>().find("validity")!=std::string::npos);}
  {Rig r;r.fix.rover=false;auto d=decode(r.command("base.apply"));d["mode"]="fixed";d["latitude"]=19.4;d["longitude"]=-99.1;d["reference_h"]=2201.5;auto c=encode(d);r.send(c);assert(r.receiver.calls==1);r.send(c);assert(r.receiver.calls==1);r.fix.base_revision=1;r.engine.tick(r.fix);assert(r.state()["operation"]["state"]=="completed");r.engine.recover();r.send(c);assert(r.receiver.calls==1);}
  {Rig r;r.fix.rover=false;r.receiver.available=false;auto d=decode(r.command("base.apply"));d["mode"]="temporary";auto c=encode(d);r.send(c);assert(r.state()["operation"]["state"]=="rejected");r.engine.recover();r.send(c);assert(r.state()["operation"]["state"]=="rejected");assert(r.receiver.calls==1);}
  {Rig r;r.fix.rover=false;auto d=decode(r.command("base.apply"));d["mode"]="fixed";d["latitude"]=19.4;d["longitude"]=-99.1;d["reference_h"]=100;r.send(encode(d));r.fix.base_revision=1;r.engine.tick(r.fix);assert(r.state()["operation"]["state"]=="applying");r.advance(46000);assert(r.state()["operation"]["state"]=="rejected");}
  for(auto p:{Position{0,3,0},Position{19.4,-99.1,2204},Position{-79.9,147,0},Position{84,30,10000}}){auto restored=geodetic(ecef(p));assert(distance(p,restored)<1e-6);}
  double e,n;assert(utm({0,3,0},31,false,e,n));assert(std::abs(e-500000)<1e-9&&std::abs(n)<1e-9);assert(!utm({19,-99,0},13,false,e,n));assert(!utm({-19,-99,0},14,false,e,n));
  // RTCM 1005 wire fixture: negative signed X/Y, positive Z, station 7.
  {uint8_t frame[25]={0xd3,0,19};auto put=[&](unsigned at,unsigned count,uint64_t value){for(unsigned i=0;i<count;++i){unsigned b=at+i+24;frame[b/8]|=((value>>(count-i-1))&1)<<(7-b%8);}};Cartesian expected=ecef({19.4,-99.1,2201.5}),actual;uint16_t station;put(0,12,1005);put(12,12,7);put(34,38,int64_t(std::llround(expected.x*10000)));put(74,38,int64_t(std::llround(expected.y*10000)));put(114,38,int64_t(std::llround(expected.z*10000)));assert(reference_station(frame,25,actual,station)&&station==7);assert(std::abs(expected.x-actual.x)<=.00005&&std::abs(expected.y-actual.y)<=.00005&&std::abs(expected.z-actual.z)<=.00005);assert(!reference_station(frame,24,actual,station));}
  {JournalStore store(root);assert(store.initialize());assert(store.commit(1,"{\"ok\":true}"));assert(!store.commit(1,"overwrite"));std::string raw;bool exists;assert(store.read(1,raw,exists)&&exists&&raw=="{\"ok\":true}");std::ofstream(root+"/00000002.tmp")<<"torn write";JournalStore reopened(root);assert(reopened.initialize());assert(reopened.read(2,raw,exists)&&!exists);assert(reopened.commit(2,"next"));std::ofstream(root+"/00000002.rec",std::ios::app)<<"corruption";assert(!reopened.read(2,raw,exists));std::remove((root+"/00000001.rec").c_str());assert(reopened.initialize());assert(!reopened.read(1,raw,exists));}
  std::cout<<"PASS: durable jobs, restart/dedup, cancellation, write uncertainty/faults, quality gates, antenna/geoid/units, base verification, ECEF/UTM, RTCM and real-file journal integrity\n";
}
int main(int argc,char **argv){
  if(argc>1&&std::string(argv[1])=="--utm"){std::cout.precision(15);for(int zone:{1,14,31,60})for(double lat:{-80.,-33.,0.,19.4,60.,84.})for(double delta:{-3.,-.1,0.,3.}){double lon=zone*6-183+delta,e,n;assert(utm({lat,lon,0},zone,lat<0,e,n));std::cout<<zone<<","<<lat<<","<<lon<<","<<e<<","<<n<<"\n";}return 0;}
  if(argc>1&&std::string(argv[1])=="--serve") {Rig r;std::string line;while(std::getline(std::cin,line)){auto d=decode(line);if(d["restart"]==true)r.engine.recover();if(d["fix"].is<JsonObject>()){auto f=d["fix"];if(f.containsKey("fixed"))r.fix.fixed=f["fixed"];if(f.containsKey("rover"))r.fix.rover=f["rover"];if(f.containsKey("station"))r.fix.station=f["station"];}
    if(d["command"].is<JsonObject>()){std::string c;serializeJson(d["command"],c);r.send(c);}if(d["advance"].is<unsigned>())r.advance(d["advance"]);std::cout<<r.engine.snapshot(r.fix)<<std::endl;}return 0;}
  assert(argc==2);tests(argv[1]);
}
