#include "survey_engine.h"
#include "survey_json.h"
#include "survey_store.h"
#include "survey_control.h"
#include <cassert>
#include <iostream>
#include <map>
#include <fstream>
#include <cstring>
using namespace survey;
struct MemoryStore:Store {
  std::map<unsigned,std::string> records;bool ready=true,fail=false,uncertain=false;
  bool initialize() override{return ready;}
  bool read(unsigned n,std::string &s,bool &exists) override {exists=records.count(n);if(exists)s=records[n];return exists||records.empty()||n>records.rbegin()->first;}
  bool commit(unsigned n,const std::string &s) override {if(fail||records.count(n))return false;records[n]=s;return !uncertain;}
};
struct ReceiverMock:Receiver {bool available=true;unsigned calls=0;BaseRequest last;bool apply(const BaseRequest &r) override {++calls;last=r;return available;}};
std::string id(unsigned n){char out[33];std::snprintf(out,sizeof(out),"%032x",n);return out;}
std::string encode(JsonDocument &d){return precise_json(d.as<JsonVariantConst>());}
DynamicJsonDocument decode(const std::string &s){DynamicJsonDocument d(32768);assert(!deserializeJson(d,s));return d;}
const char *fixture=R"({"crs":"wgs84_utm","frame":"WGS84","epoch":2026.7,"reference_confirmed":true,"zone":14,"south":false,"units":"m","vertical":"ellipsoid","rover_model":"Test reference","rover_height":2,"rover_offset":0,"rover_radius":0,"rover_method":"vertical","base_model":"Test reference","base_height":1.5,"base_offset":0,"base_radius":0,"base_method":"vertical","antenna_confirmed":true,"base_name":"Test control","station":7,"base_mode":"known","base_lat":19.4,"base_lon":-99.1,"base_ground_h":2200,"base_tolerance":0.02,"duration":2,"min_samples":3,"h_limit":0.03,"v_limit":0.05,"correction_limit":3000})";
struct Rig {
  MemoryStore store;ReceiverMock receiver;Engine engine;Fix fix;unsigned next=10;std::string job=id(1);
  Rig():engine(store,receiver){fix.now=fix.received=10000;fix.epoch=1473000000000ULL;fix.rover=fix.profile_ok=fix.position_valid=fix.fixed=fix.linked=fix.reference_valid=true;fix.position={19.4001,-99.1001,2204};fix.reference=ecef({19.4,-99.1,2201.5});fix.station=7;fix.hacc=.01;fix.vacc=.02;fix.satellites=30;std::strcpy(fix.utc,"2026-09-10T12:00:00Z");engine.recover();}
  DynamicJsonDocument state(){return decode(engine.snapshot(fix));}
  std::string command(const char *op,unsigned n=0){DynamicJsonDocument d(16384);d["id"]=id(n?n:next++);d["op"]=op;d["job"]=job;d["revision"]=1;d["name"]="Bench fixture";d["point_id"]="1001";d["code"]="BM";d["description"]="Test observation";d["confirm"]=true;return encode(d);}
  void send(const std::string &s){engine.command(s.c_str(),fix);}
  void setup(){send(command("job.create",1));auto d=decode(command("job.configure",2));d["revision"]=0;auto c=decode(fixture);d["config"]=c.as<JsonVariantConst>();send(encode(d));assert(state()["jobs"][0]["revision"]==1);}
  void advance(unsigned ms=1000){fix.now+=ms;fix.received=fix.now;fix.epoch+=ms;engine.tick(fix);}
};
std::string target_command(Rig &r,const char *name="CP1"){
  auto d=decode(r.command("target.create"));auto t=d.createNestedObject("target");t["id"]=name;t["kind"]="control";t["source"]="Independent test control certificate";t["reference_confirmed"]=true;t["independent_source"]=true;
  double e,n;assert(utm(r.fix.position,14,false,e,n));t["easting"]=e;t["northing"]=n;t["height"]=2202.;auto c=decode(fixture);auto ref=t.createNestedObject("reference");for(const char *key:{"crs","frame","epoch","zone","south","units","vertical"})ref[key]=c[key];return encode(d);
}
std::string line_command(Rig &r,const char *point,const char *line,const char *action,const char *previous=""){
  auto d=decode(r.command("collect.start"));d["point_id"]=point;auto l=d.createNestedObject("line");l["id"]=line;l["action"]=action;l["previous_point"]=previous;return encode(d);
}
DynamicJsonDocument line_list(Rig &r){return decode(r.engine.read(("{\"view\":\"lines\",\"offset\":0,\"job\":\""+r.job+"\"}").c_str(),r.fix));}
void line_tests(){
  {Rig r;r.setup();auto first=line_command(r,"V1","L1","start");r.send(first);r.advance();r.advance();r.engine.recover();r.send(first);assert(line_list(r)["lines"][0]["vertices"]==1&&line_list(r)["lines"][0]["state"]=="open");
    r.send(line_command(r,"V2","L1","continue","old"));assert(r.state()["operation"]["state"]=="rejected");auto wrong=decode(line_command(r,"V2","L1","continue","V1"));wrong["code"]="OTHER";r.send(encode(wrong));assert(r.state()["operation"]["state"]=="rejected");
    r.send(line_command(r,"V2","L1","continue","V1"));r.advance();r.advance();r.send(line_command(r,"V3","L1","end","V2"));r.advance();r.advance();r.engine.recover();auto list=line_list(r);assert(list["lines"][0]["state"]=="closed"&&list["lines"][0]["vertices"]==3);assert(r.state()["last_point"]["line_previous"]=="V2");
    r.send(line_command(r,"V4","L1","start"));assert(r.state()["operation"]["state"]=="rejected");r.send(line_command(r,"V4","L1","continue","V3"));assert(r.state()["operation"]["state"]=="rejected");}
  for(const char *failure:{"quality","cancel","restart","delete","code","setup"}){
    Rig r;r.setup();r.send(line_command(r,"V1","L1","start"));r.advance();r.advance();
    if(std::strcmp(failure,"delete")==0||std::strcmp(failure,"code")==0){auto edit=decode(r.command("point.edit"));edit["point_id"]="V1";edit["note"]="";edit["reason"]="Line vertex audit";edit["deleted"]=std::strcmp(failure,"delete")==0;if(std::strcmp(failure,"code")==0)edit["code"]="EDITED";r.send(encode(edit));edit["id"]=id(100);edit["revision"]=2;edit["deleted"]=false;edit["code"]="BM";r.send(encode(edit));}
    else if(std::strcmp(failure,"setup")==0){auto config=decode(r.command("job.configure"));config["config"]=decode(fixture).as<JsonVariantConst>();r.send(encode(config));}
    else {r.send(line_command(r,"V2","L1","continue","V1"));if(std::strcmp(failure,"quality")==0){r.fix.fixed=false;r.advance();r.fix.fixed=true;}else if(std::strcmp(failure,"cancel")==0)r.send(r.command("collect.cancel"));}
    r.engine.recover();assert(line_list(r)["lines"][0]["state"]=="broken");assert(line_list(r)["lines"][0]["vertices"]==1);r.send(line_command(r,"V2","L1","continue","V1"));assert(r.state()["operation"]["state"]=="rejected");
  }
  {Rig r;r.setup();r.send(line_command(r,"V1","L1","start"));r.advance();r.advance();r.fix.reference.x+=.005;r.send(line_command(r,"V2","L1","continue","V1"));assert(r.state()["operation"]["state"]=="rejected");assert(r.state()["operation"]["message"].as<std::string>().find("Base reference changed")!=std::string::npos);}
  {Rig r;r.setup();r.send(line_command(r,"V1","L1","start"));r.advance();r.advance();auto next=line_command(r,"V2","L1","continue","V1");r.send(next);r.advance();r.store.uncertain=true;r.advance();r.store.uncertain=false;r.engine.recover();r.send(next);assert(r.state()["operation"]["state"]=="completed"&&line_list(r)["lines"][0]["vertices"]==2);}
  {Rig r;r.setup();for(unsigned i=0;i<64;++i){auto key=std::to_string(i);r.send(line_command(r,key.c_str(),key.c_str(),"start"));r.advance();r.advance();}assert(r.state()["lines_used"]==64);r.send(line_command(r,"OVER","OVER","start"));assert(r.state()["operation"]["state"]=="rejected");auto list=line_list(r);assert(list["total"]==64&&list["lines"].size()==25&&list["next"]==25);}
  std::cout<<"PASS: line continuity, immutable vertices, gaps, deletion/code/setup breaks, restart, reference changes, uncertain writes and limits\n";
}
void tests(const std::string &root){
  line_tests();
  {Rig r;r.setup();auto target=decode(target_command(r));target["target"]["kind"]="design";target["target"]["independent_source"]=false;r.send(encode(target));auto request=decode(r.command("collect.start"));auto c=request.createNestedObject("comparison");c["purpose"]="stake";c["phase"]="intermediate";c["target_id"]="CP1";c["h_tolerance"]=.03;c["v_tolerance"]=.05;r.send(encode(request));r.advance();r.advance();auto s=r.state();assert(s["last_point"]["kind"]=="stake"&&s["last_point"]["comparison"]["pass"]==true&&s["last_point"]["comparison"]["independent_control"]==false);r.engine.recover();assert(r.state()["last_point"]["comparison"]["reference"]["kind"]=="design");request["id"]=id(95);request["point_id"]="STAKE2";r.send(encode(request));r.fix.fixed=false;r.advance();assert(r.state()["jobs"][0]["points"]==1&&r.state()["operation"]["state"]=="rejected");}
  {auto d=decode("{\"quote\\\"key\":\"line\\ntext\",\"a\":[true,false,null,18446744073709551615],\"e\":489489.917803906,\"n\":2145101.645512206}");auto round=decode(encode(d));assert(std::abs(round["e"].as<double>()-d["e"].as<double>())<1e-8&&std::abs(round["n"].as<double>()-d["n"].as<double>())<1e-8);assert(round["a"][3].as<uint64_t>()==UINT64_MAX&&round["quote\"key"]=="line\ntext");}
  {Rig r;r.setup();auto request=decode(r.command("job.configure",2));request["revision"]=0;request["config"]=decode(fixture).as<JsonVariantConst>();std::string legacy;serializeJson(request,legacy);auto event=decode(r.store.records[2]);event.remove("payload_format");event["payload_crc"]=crc32(legacy);r.store.records[2]=encode(event);r.engine.recover();r.send(encode(request));assert(r.state()["operation"]["state"]=="completed");}
  {Rig r;r.setup();auto target=decode(target_command(r));r.send(encode(target));target["target"]["northing"]=target["target"]["northing"].as<double>()+.00001;r.send(encode(target));assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();auto config=decode(r.command("job.configure"));config["config"]=decode(fixture).as<JsonVariantConst>();config["config"]["units"]="ft";r.send(encode(config));auto target=decode(target_command(r));target["revision"]=2;target["target"]["reference"]["units"]="ft";for(const char *key:{"easting","northing","height"})target["target"][key]=target["target"][key].as<double>()/.3048;target["target"]["height"]=target["target"]["height"].as<double>()+.1;r.send(encode(target));assert(r.state()["operation"]["state"]=="completed");auto check=decode(r.command("collect.start"));check["revision"]=2;auto c=check.createNestedObject("comparison");c["purpose"]="check";c["phase"]="end";c["target_id"]="CP1";c["h_tolerance"]=.03;c["v_tolerance"]=.05;r.send(encode(check));r.advance();r.advance();auto state=r.state();assert(state["last_point"]["comparison"]["units"]=="ft"&&state["last_point"]["comparison"]["pass"]==false);assert(std::abs(state["last_point"]["comparison"]["delta_h"].as<double>()+.1)<1e-7);}
  {Rig r;r.setup();r.send(target_command(r));auto check=decode(r.command("collect.start"));auto c=check.createNestedObject("comparison");c["purpose"]="check";c["phase"]="start";c["target_id"]="CP1";c["h_tolerance"]=.03;c["v_tolerance"]=.05;r.send(encode(check));r.advance();r.advance();auto saved=r.state();assert(saved["last_point"]["comparison"]["pass"]==true&&saved["last_point"]["comparison"]["independent_control"]==true);assert(saved["last_point"]["kind"]=="check");
    check["id"]=id(90);check["point_id"]="1002";c["purpose"]="repeat";c["reference_point"]="1001";c["phase"]="end";r.send(encode(check));r.advance();r.advance();saved=r.state();assert(saved["jobs"][0]["points"]==2&&saved["last_point"]["comparison"]["pass"]==true&&saved["last_point"]["comparison"]["independent_control"]==false);r.engine.recover();assert(r.state()["last_point"]["comparison"]["reference"]["id"]=="1001");
    check["id"]=id(91);check["point_id"]="1003";c["h_tolerance"]=0;r.send(encode(check));assert(r.state()["operation"]["state"]=="rejected");c["h_tolerance"]=.03;c["reference_point"]="missing";r.send(encode(check));assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();auto target=decode(target_command(r));target["target"]["easting"]=target["target"]["easting"].as<double>()+.03;target["target"]["northing"]=target["target"]["northing"].as<double>()+.04;target["target"]["height"]=2202.1;r.send(encode(target));auto check=decode(r.command("collect.start"));auto c=check.createNestedObject("comparison");c["purpose"]="check";c["phase"]="intermediate";c["target_id"]="CP1";c["h_tolerance"]=.04;c["v_tolerance"]=.05;r.send(encode(check));r.advance();r.advance();auto s=r.state();auto comparison=s["last_point"]["comparison"];assert(comparison["pass"]==false&&comparison["horizontal_pass"]==false&&comparison["vertical_pass"]==false);assert(std::abs(comparison["delta_h"].as<double>()+.1)<1e-6&&std::abs(comparison["horizontal"].as<double>()-.05)<1e-6);assert(s["jobs"][0]["points"]==1);}
  {Rig r;r.setup();auto original=target_command(r);r.send(original);assert(r.state()["operation"]["state"]=="completed");assert(r.state()["targets_used"]==1&&r.state()["jobs"][0]["points"]==0);r.engine.recover();r.send(original);assert(r.state()["targets_used"]==1);auto page=decode(r.engine.read(("{\"view\":\"targets\",\"offset\":0,\"job\":\""+r.job+"\"}").c_str(),r.fix));assert(page["targets"][0]["source"]=="Independent test control certificate"&&page["targets"][0]["fix"].isNull());
    r.send(target_command(r));assert(r.state()["operation"]["state"]=="rejected");auto bad=decode(target_command(r,"CP2"));bad["target"]["reference"]["units"]="ft";r.send(encode(bad));assert(r.state()["operation"]["state"]=="rejected");bad=decode(target_command(r,"CP2"));bad["target"]["independent_source"]=false;r.send(encode(bad));assert(r.state()["operation"]["state"]=="rejected");bad=decode(target_command(r,"CP2"));bad["revision"]=0;r.send(encode(bad));assert(r.state()["operation"]["state"]=="rejected");
    for(unsigned i=1;i<64;++i)r.send(target_command(r,("REF"+std::to_string(i)).c_str()));assert(r.state()["targets_used"]==64);r.send(target_command(r,"OVER"));assert(r.state()["operation"]["state"]=="rejected");r.engine.recover();assert(r.state()["storage_ready"]==true&&r.state()["targets_used"]==64);}
  {Rig r;r.setup();for(unsigned i=0;i<30;++i){auto c=decode(r.command("collect.start"));c["point_id"]=std::to_string(1000+i);r.send(encode(c));r.advance();r.advance();}
    auto read=[&](const std::string &request){return decode(r.engine.read(request.c_str(),r.fix));};
    auto list=read("{\"view\":\"points\",\"job\":\""+r.job+"\",\"offset\":0}");assert(list["total"]==30&&list["points"].size()==25&&list["next"]==25);
    auto edit=decode(r.command("point.edit"));edit["point_id"]="1000";edit["revision"]=1;edit["code"]="UPDATED";edit["description"]="Edited description";edit["note"]="Check pole";edit["deleted"]=true;edit["reason"]="Test audit";auto request=encode(edit);r.send(request);assert(r.state()["operation"]["state"]=="completed");r.engine.recover();r.send(request);assert(r.state()["operation"]["state"]=="completed");
    auto detail=read("{\"view\":\"point\",\"job\":\""+r.job+"\",\"point\":\"1000\"}");assert(detail["point"]["code"]=="UPDATED"&&detail["point"]["original_metadata"]["code"]=="BM"&&detail["point"]["deleted"]==true&&detail["point"]["edit_revision"]==2);assert(std::abs(detail["point"]["height"].as<double>()-2202)<1e-6);
    list=read("{\"view\":\"points\",\"job\":\""+r.job+"\",\"offset\":25}");assert(list["total"]==29&&list["points"].size()==4);assert(!list.containsKey("next"));
    edit["id"]=id(400);r.send(encode(edit));assert(r.state()["operation"]["state"]=="rejected");edit["revision"]=2;edit["deleted"]=false;r.send(encode(edit));assert(r.state()["operation"]["state"]=="completed");
    assert(read("{\"view\":\"points\",\"job\":\""+r.job+"\",\"offset\":0,\"at\":1}")["error"]=="job_changed_reload");
    unsigned cursor=0,total=0;MemoryStore restored;do{auto page=read("{\"view\":\"backup\",\"job\":\""+r.job+"\",\"offset\":"+std::to_string(cursor)+"}");assert(page["format"]=="TopoRTK job journal"&&page["records"].size()<=3);for(auto row:page["records"].as<JsonArray>()){std::string raw=row["json"];assert(crc32(raw)==row["crc32"].as<uint32_t>());assert(raw==r.store.records[row["sequence"]]);restored.records[++total]=raw;}cursor=page["next"]|0U;}while(cursor);
    assert(total==r.store.records.size());Engine reopened(restored,r.receiver);reopened.recover();auto recovered=decode(reopened.snapshot(r.fix));assert(recovered["storage_ready"]==true&&recovered["jobs"][0]["points"]==30);auto restoredPoint=decode(reopened.read(("{\"view\":\"point\",\"job\":\""+r.job+"\",\"point\":\"1000\"}").c_str(),r.fix));assert(restoredPoint["point"]["edit_revision"]==3&&restoredPoint["point"]["deleted"]==false);}
  {Control c;char a[33]={},b[33]={};c.reset("123456");
    assert(c.takeover("bad",id(2).c_str(),1,a,33)==400);
    assert(c.takeover(id(1).c_str(),id(2).c_str(),1,a,32)==400);
    assert(c.takeover(id(1).c_str(),id(2).c_str(),1,a,33)==200);
    assert(c.authorized(a,2,true));
    assert(c.takeover(id(3).c_str(),id(4).c_str(),3,b,33)==200);
    assert(!c.authorized(a,4,true)&&c.authorized(b,4,false));
    c.release(a,5);assert(c.authorized(b,5,false));
    // A repeated client ID still rotates the token; stale tabs cannot retain control.
    assert(c.takeover(id(3).c_str(),id(5).c_str(),6,a,33)==200);
    assert(!c.authorized(b,7,true)&&c.authorized(a,7,false));
    assert(!c.authorized(a,120006,false));
    assert(c.takeover(id(1).c_str(),id(6).c_str(),120007,b,33)==200);
    c.reset("654321");assert(!c.authorized(b,120008,false));
    // PIN failure throttling belongs only to Base pairing.
    for(int n=0;n<5;++n)assert(c.claim("000000",id(1).c_str(),id(2).c_str(),120010+n,a,33)==403);
    assert(c.takeover(id(1).c_str(),id(7).c_str(),120020,b,33)==200);
    c.release(b,120021);assert(!c.authorized(b,120022,false));
  }
  {Control c;char token[33];assert(c.claim("",id(1).c_str(),id(2).c_str(),1,token,33)==400);c.reset("123456");for(int i=0;i<5;++i)assert(c.claim("000000",id(1).c_str(),id(2).c_str(),100+i,token,33)==403);assert(c.claim("123456",id(1).c_str(),id(2).c_str(),200,token,33)==429);assert(c.claim("123456",id(1).c_str(),id(2).c_str(),60100,token,33)==200);assert(c.authorized(token,60100,false));assert(c.claim("123456",id(3).c_str(),id(4).c_str(),60200,token,33)==409);assert(!c.authorized(id(4).c_str(),60300,true));assert(c.authorized(id(2).c_str(),100000,true));assert(c.authorized(id(2).c_str(),219999,false));assert(!c.authorized(id(2).c_str(),220000,false));assert(c.claim("123456",id(3).c_str(),id(4).c_str(),220001,token,33)==200);c.release(token,220002);assert(!c.authorized(token,220003,false));c.reset("654321");assert(c.claim("123456",id(3).c_str(),id(4).c_str(),220004,token,33)==403);}
  {Rig r;r.setup();const auto c=r.command("collect.start");r.send(c);assert(r.state()["collection"]["samples"]==1);r.engine.tick(r.fix);assert(r.state()["collection"]["samples"]==1);r.advance();r.advance();auto s=r.state();assert(s["jobs"][0]["points"]==1);assert(std::abs(s["last_point"]["ground_ellipsoidal_h_m"].as<double>()-2202)<1e-6);assert(s["last_point"]["base_control_verified"]==true);assert(s["last_point"]["configuration_revision"]==1);const auto count=r.store.records.size();r.send(c);assert(r.store.records.size()==count);r.engine.recover();r.send(c);assert(r.state()["operation"]["state"]=="completed");assert(r.state()["jobs"][0]["points"]==1);r.send(r.command("collect.start"));assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();auto c=r.command("collect.start");r.send(c);r.engine.recover();r.send(c);assert(r.state()["operation"]["state"]=="interrupted");assert(r.state()["jobs"][0]["points"]==0);}
  for(int failure=0;failure<10;++failure){Rig r;r.setup();r.send(r.command("collect.start"));switch(failure){case 0:r.fix.fixed=false;break;case 1:r.fix.hacc=.04;break;case 2:r.fix.vacc=.06;break;case 3:r.fix.correction_age=3001;break;case 4:r.fix.station=8;break;case 5:r.fix.reference.x+=.01;break;case 6:r.fix.profile_ok=false;break;case 7:r.fix.position_valid=false;break;case 8:r.fix.now+=1501;break;case 9:r.fix.epoch-=1000;break;}r.engine.tick(r.fix);assert(r.state()["collection"]["active"]==false);assert(r.state()["jobs"][0]["points"]==0);assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();r.send(r.command("collect.start"));r.send(r.command("storage.recover"));assert(r.state()["collection"]["active"]==true);auto cancel=r.command("collect.cancel");r.send(cancel);auto count=r.store.records.size();r.engine.recover();r.send(cancel);assert(r.state()["operation"]["state"]=="completed"&&r.store.records.size()==count);}
  {Rig r;auto c=r.command("job.create",1);r.store.uncertain=true;r.send(c);assert(!r.state()["storage_ready"].as<bool>());r.store.uncertain=false;r.engine.recover();r.send(c);assert(r.state()["jobs"].size()==1);assert(r.state()["operation"]["state"]=="completed");auto other=decode(c);other["name"]="Changed";r.send(encode(other));assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();r.send(r.command("collect.start"));r.advance();r.store.fail=true;r.advance();assert(r.state()["jobs"][0]["points"]==0);assert(r.state()["operation"]["state"]=="rejected");r.store.fail=false;r.engine.recover();assert(r.state()["jobs"][0]["points"]==0);}
  {Rig r;r.store.ready=false;r.engine.recover();r.send(r.command("job.create"));assert(r.store.records.empty());}
  {Rig r;r.setup();auto d=decode(r.command("job.configure"));d["revision"]=0;d["config"]=decode(fixture).as<JsonVariantConst>();r.send(encode(d));assert(r.state()["operation"]["state"]=="rejected");d["revision"]=1;d["config"]["south"]=nullptr;r.send(encode(d));assert(r.state()["operation"]["state"]=="rejected");d["config"]["south"]=false;d["config"]["rover_method"]="slant";d["config"]["rover_radius"]=1;d["config"]["rover_height"]=.5;r.send(encode(d));assert(r.state()["operation"]["state"]=="rejected");}
  {Rig r;r.setup();auto d=decode(r.command("job.configure"));d["config"]=decode(fixture).as<JsonVariantConst>();auto c=d["config"];c["base_mode"]="temporary";c["temporary_confirmed"]=true;c["rover_method"]="slant";c["rover_height"]=2.5;c["rover_radius"]=.7;c["rover_offset"]=.1;c["units"]="ft";c["vertical"]="constant_geoid";c["geoid_name"]="Bench local model";c["geoid_n"]=-30;c["geoid_lat"]=19.4;c["geoid_lon"]=-99.1;c["geoid_radius"]=100;r.send(encode(d));assert(r.state()["jobs"][0]["revision"]==2);auto collect=decode(r.command("collect.start"));collect["revision"]=2;r.send(encode(collect));r.advance();r.advance();auto p=r.state()["last_point"].as<JsonObjectConst>();auto s=r.state();assert(s["last_point"]["base_control_verified"]==false);assert(std::abs(s["last_point"]["height"].as<double>()-(2204-2.5+30)/.3048)<1e-5);r.fix.position.latitude+=.1;assert(r.state()["block_reason"].as<std::string>().find("validity")!=std::string::npos);}
  {Rig r;r.fix.rover=false;auto d=decode(r.command("base.apply"));d["mode"]="fixed";d["latitude"]=19.4;d["longitude"]=-99.1;d["reference_h"]=2201.5;auto c=encode(d);r.send(c);assert(r.receiver.calls==1);r.send(c);assert(r.receiver.calls==1);r.fix.base_revision=1;r.engine.tick(r.fix);assert(r.state()["operation"]["state"]=="completed");r.engine.recover();r.send(c);assert(r.receiver.calls==1);}
  {Rig r;r.fix.rover=false;r.receiver.available=false;auto d=decode(r.command("base.apply"));d["mode"]="temporary";auto c=encode(d);r.send(c);assert(r.state()["operation"]["state"]=="rejected");r.engine.recover();r.send(c);assert(r.state()["operation"]["state"]=="rejected");assert(r.receiver.calls==1);}
  {Rig r;r.fix.rover=false;auto d=decode(r.command("base.apply"));d["mode"]="fixed";d["latitude"]=19.4;d["longitude"]=-99.1;d["reference_h"]=100;r.send(encode(d));r.fix.base_revision=1;r.engine.tick(r.fix);assert(r.state()["operation"]["state"]=="applying");r.advance(46000);assert(r.state()["operation"]["state"]=="rejected");}
  for(auto p:{Position{0,3,0},Position{19.4,-99.1,2204},Position{-79.9,147,0},Position{84,30,10000}}){auto restored=geodetic(ecef(p));assert(distance(p,restored)<1e-6);}
  double e,n;assert(utm({0,3,0},31,false,e,n));assert(std::abs(e-500000)<1e-9&&std::abs(n)<1e-9);assert(!utm({19,-99,0},13,false,e,n));assert(!utm({-19,-99,0},14,false,e,n));
  // RTCM 1005 wire fixture: negative signed X/Y, positive Z, station 7.
  {uint8_t frame[25]={0xd3,0,19};auto put=[&](unsigned at,unsigned count,uint64_t value){for(unsigned i=0;i<count;++i){unsigned b=at+i+24;frame[b/8]|=((value>>(count-i-1))&1)<<(7-b%8);}};Cartesian expected=ecef({19.4,-99.1,2201.5}),actual;uint16_t station;put(0,12,1005);put(12,12,7);put(34,38,int64_t(std::llround(expected.x*10000)));put(74,38,int64_t(std::llround(expected.y*10000)));put(114,38,int64_t(std::llround(expected.z*10000)));assert(reference_station(frame,25,actual,station)&&station==7);assert(std::abs(expected.x-actual.x)<=.00005&&std::abs(expected.y-actual.y)<=.00005&&std::abs(expected.z-actual.z)<=.00005);assert(!reference_station(frame,24,actual,station));}
  {JournalStore store(root);assert(store.initialize());assert(store.commit(1,"{\"ok\":true}"));assert(!store.commit(1,"overwrite"));std::string raw;bool exists;assert(store.read(1,raw,exists)&&exists&&raw=="{\"ok\":true}");std::ofstream(root+"/00000002.tmp")<<"torn write";JournalStore reopened(root);assert(reopened.initialize());assert(reopened.read(2,raw,exists)&&!exists);assert(reopened.commit(2,"next"));std::ofstream(root+"/00000002.rec",std::ios::app)<<"corruption";assert(!reopened.read(2,raw,exists));std::remove((root+"/00000001.rec").c_str());assert(reopened.initialize());assert(!reopened.read(1,raw,exists));}
  std::cout<<"PASS: durable jobs, restart/dedup, cancellation, write uncertainty/faults, quality gates, antenna/geoid/units, base verification, ECEF/UTM, RTCM and real-file journal integrity\n";
}
int main(int argc,char **argv){
  if(argc>1&&std::string(argv[1])=="--utm"){std::cout.precision(15);for(int zone:{1,14,31,60})for(double lat:{-80.,-33.,0.,19.4,60.,84.})for(double delta:{-3.,-.1,0.,3.}){double lon=zone*6-183+delta,e,n;assert(utm({lat,lon,0},zone,lat<0,e,n));std::cout<<zone<<","<<lat<<","<<lon<<","<<e<<","<<n<<"\n";}return 0;}
  if(argc>1&&std::string(argv[1])=="--serve") {Rig r;std::string line;while(std::getline(std::cin,line)){auto d=decode(line);if(d["query"].is<JsonObject>()){std::string q;serializeJson(d["query"],q);std::cout<<r.engine.read(q.c_str(),r.fix)<<std::endl;continue;}if(d["restart"]==true)r.engine.recover();if(d["fix"].is<JsonObject>()){auto f=d["fix"];if(f.containsKey("fixed"))r.fix.fixed=f["fixed"];if(f.containsKey("rover"))r.fix.rover=f["rover"];if(f.containsKey("station"))r.fix.station=f["station"];}
    if(d["command"].is<JsonObject>()){std::string c=precise_json(d["command"]);r.send(c);}if(d["advance"].is<unsigned>())r.advance(d["advance"]);std::cout<<r.engine.snapshot(r.fix)<<std::endl;}return 0;}
  assert(argc==2);tests(argv[1]);
}
