[platformio]
default_envs = unit_a

[env]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 460800
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
lib_deps =
    moononournation/GFX Library for Arduino@1.5.5
    robtillaart/TCA9554@0.1.2
    bblanchon/ArduinoJson@6.21.5

[env:unit_a]
upload_port = COM4
monitor_port = COM4
build_flags =
    ${env.build_flags}
    -DTOPORTK_DISPLAY_ROTATION=0
    -DTOPORTK_UNIT_ID=1

[env:unit_b]
upload_port = COM10
monitor_port = COM10
build_flags =
    ${env.build_flags}
    -DTOPORTK_DISPLAY_ROTATION=0
    -DTOPORTK_UNIT_ID=2
