#pragma once
const char kDiagnosticPage[] PROGMEM=R"HTML(<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TopoRTK · Link test</title><style>
*{box-sizing:border-box}body{font:16px/1.5 system-ui;background:#eef2f5;color:#172d3b;margin:0}main{max-width:800px;margin:auto;padding:24px}section{background:white;border:1px solid #d2dde4;border-radius:14px;padding:20px;margin:18px 0}label{display:block;margin:12px 0}input,select,button{font:inherit;padding:12px;border:1px solid #a6bac5;border-radius:7px;max-width:100%}button{background:#166546;color:white;cursor:pointer;margin:8px 8px 0 0}input,select{display:block;width:100%}pre{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#155a77}.muted{color:#526674}h1{margin-bottom:0}#message{padding:12px;background:#e3eaf0}button:disabled{opacity:.5}</style>
<main><a href="/survey">← Survey</a><h1>Link test</h1><p class="muted">Runs on the two instruments. The tablet can disconnect during the test.</p><p id="message">Connecting…</p>
<section><h2>1. Prepare both instruments</h2><p>Keep antennas connected. Use the same six-digit test code and settings on Base and Rover. Arm each instrument from its own page before moving apart. Survey writes are locked during the test.</p><label>Base control PIN, if this is the Base<input id="pin" inputmode="numeric" maxlength="6" autocomplete="off"></label><button id="control">Take control</button>
<label>Test code<input id="run" inputmode="numeric" pattern="[0-9]{6}" maxlength="6"></label><label>Link<select id="transport"><option value="sik">SiK radio</option><option value="wifi">Wi-Fi</option></select></label><label>Traffic<select id="mode"><option value="0">Base → Rover</option><option value="1">Rover → Base</option><option value="2">Both directions</option></select></label><label>Duration<select id="seconds"><option>30</option><option selected>60</option><option>120</option><option>300</option></select></label><label>Bytes per second, each sending instrument<select id="rate"><option>200</option><option selected>1000</option><option>3000</option></select></label><label><input type="checkbox" id="confirm" style="width:auto;display:inline"> Antennas and wiring are ready; no survey occupation is active.</label><button id="probe">Check radio wiring</button><button id="arm">Arm this instrument</button><button id="cancel">Cancel test</button></section>
<section><h2>2. Results</h2><p>Missing peer results mean the pair has not passed. Results remain on each instrument after the tablet disconnects; the latest result survives restart.</p><p id="result" aria-live="polite">Waiting…</p><p id="metrics"></p><p id="wiring"></p><button id="download">Download report</button><p class="muted">This checks synthetic data delivery, not RTK accuracy. SiK: 57,600 baud. Bluetooth is not available yet.</p></section></main><script>
'use strict';const $=id=>document.getElementById(id);let token='',state=null;
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,'0')).join('');const client=random();$('run').value=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);
async function post(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function message(s){$('message').textContent=s;}
$('control').onclick=async()=>{try{const d=await post('/api/v1/control',{client,pin:$('pin').value});token=d.token;message('Control acquired.')}catch(e){message(e.message)}};
$('arm').onclick=async()=>{try{if(!$('confirm').checked)throw Error('Confirm preparation first.');await post('/api/v1/diagnostic',{op:'arm',run:Number($('run').value),transport:$('transport').value,mode:Number($('mode').value),seconds:Number($('seconds').value),rate:Number($('rate').value),confirm:true});message('Request queued; check the state below.')}catch(e){message(e.message)}};
$('probe').onclick=async()=>{try{if(!$('confirm').checked)throw Error('Confirm preparation first.');await post('/api/v1/diagnostic',{op:'probe',confirm:true});message('Checking the local radio UART...')}catch(e){message(e.message)}};
$('cancel').onclick=async()=>{try{await post('/api/v1/diagnostic',{op:'cancel',run:state?.run});message('Cancellation requested.')}catch(e){message(e.message)}};
$('download').onclick=()=>{if(!state)return;const report=state.busy?state:(state.last_report||state);const a=document.createElement('a');const u=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.href=u;a.download='TopoRTK-link-'+(report.run||'last')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
async function poll(){try{const r=await fetch('/api/v1/diagnostic',{cache:'no-store'});if(!r.ok)throw Error('Instrument unavailable');state=await r.json();const d=state.state==='idle'&&state.last_report?state.last_report:state;$('result').textContent=d.state==='done'?(d.pair_pass?'PASS: both instruments received every test packet.':'Not passed: check missing packets, errors and the peer report.'):(d.state+' / '+(d.reason||''));$('metrics').textContent='Sent '+(d.sent||0)+' / '+(d.expected_tx||0)+'; received '+(d.received||0)+' / '+(d.expected_rx||0)+'; errors '+(d.errors||0)+'; duplicates '+(d.duplicates||0)+'; out of order '+(d.reordered||0)+'; longest receive gap '+(d.max_gap_ms||0)+' ms'+(state.busy?'; '+state.remaining_seconds+' seconds remaining':'');$('wiring').textContent=state.radio_probe;$('arm').disabled=state.busy;$('probe').disabled=state.busy;$('cancel').disabled=!state.busy;}catch(e){message('Disconnected. The instrument continues its bounded test; reconnect to retrieve results.')}finally{setTimeout(poll,1000)}}poll();
</script></html>)HTML";
