#pragma once
static const char kSurveyPage[] = R"SURVEY(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>TopoRTK · Survey</title>
<style>
:root{font:16px system-ui,sans-serif;color:#edf4f7;background:#101b22;--muted:#a6b8c4;--line:#354852;--accent:#a6ef65}*{box-sizing:border-box}body{margin:0}main{max-width:1040px;margin:auto;padding:20px}header{display:flex;align-items:center;justify-content:space-between;gap:16px}h1{font-size:1.55rem;margin:0}h2{font-size:1.3rem;margin:0 0 16px}h3{font-size:1rem;margin:0 0 12px}p{line-height:1.5}a{color:var(--accent)}.sub,small,.help{color:var(--muted);font-size:.88rem;line-height:1.5}.sub{margin:5px 0}.banner{padding:12px 16px;background:#24343e;border-left:4px solid #e9be66;margin:18px 0;overflow-wrap:anywhere}.good{border-color:var(--accent)}nav{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}button,input,select,textarea{font:inherit;border-radius:7px;border:1px solid #526873;min-height:46px}button{cursor:pointer;padding:10px 16px;background:#263b46;color:#edf4f7}button.primary,nav button[aria-selected=true]{background:var(--accent);color:#172316;border-color:var(--accent);font-weight:650}button:disabled{opacity:.45;cursor:not-allowed}input,select,textarea{width:100%;background:#101b22;color:#edf4f7;padding:10px}input[type=checkbox]{width:22px;min-height:22px;flex-shrink:0}label{display:flex;flex-direction:column;gap:6px;color:var(--muted);font-size:.9rem}label.check{flex-direction:row;align-items:center;color:#edf4f7;margin:16px 0;line-height:1.5}section,.card{background:#192a34;border:1px solid var(--line);border-radius:12px;padding:20px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.wide{grid-column:1/-1}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.row>*{min-width:0}.row label{flex:1}.hidden,[hidden]{display:none!important}.metric{font-size:2rem;color:var(--accent);margin:6px 0}.jobs{display:grid;gap:10px}.job{display:flex;justify-content:space-between;align-items:center;gap:12px;border-bottom:1px solid var(--line);padding:12px 0;overflow-wrap:anywhere}.job span{min-width:0}.job button{flex-shrink:0}.details{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.6;color:#cad9e2}.busy{color:#e9be66}fieldset{border:0;padding:0;margin:0;min-width:0}details{margin-top:14px}summary{cursor:pointer;color:var(--muted)}:focus-visible{outline:3px solid #e9be66;outline-offset:3px}@media(max-width:620px){main{padding:14px}.grid{grid-template-columns:1fr}section,.card{padding:16px}.row{align-items:stretch}header{align-items:start}.metric{font-size:1.6rem}nav button{flex:1}}
</style></head><body><main>
<header><div><h1>TopoRTK <span class="sub">/ Survey</span></h1><p class="sub" id="instrument">Connecting to instrument…</p></div><a id="liveStatus" href="/ui/v1/">Live status ↗</a></header>
<div class="banner" id="connection" role="status">Waiting for live data. Controls are locked.</div>
<details id="pairPanel"><summary id="controlState">View only · Pair to control</summary><p class="help">On this instrument, open Link → Phone / Tablet → Show key. Enter the six-digit WEB CONTROL PIN. One browser can control the instrument at a time; control expires after two minutes without contact.</p><form id="pair" class="row"><label>Control PIN<input name="pin" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="off" required></label><button type="submit">Take control</button><button type="button" id="release">Release control</button></form></details>
<nav role="tablist" aria-label="Survey workflow"><button data-tab="jobs" aria-selected="true">1 · Jobs</button><button data-tab="setup" aria-selected="false">2 · Setup</button><button data-tab="collect" aria-selected="false">3 · Collect</button><button data-tab="base" aria-selected="false" hidden>Base setup</button></nav>
<div class="banner" id="message" role="status" hidden></div><div id="retryPanel" hidden><p class="help">A previous request has no confirmed result. Retry checks the same request, without duplicating it.</p><button id="retry" data-write>Check / retry request</button></div>
<section data-panel="jobs"><h2>Jobs on this Rover</h2><p class="help">Jobs, configuration revisions and collected points are saved on the instrument’s SD card and restored on startup. A new job starts unconfigured.</p><form id="create" class="row"><label>New job name<input name="name" maxlength="48" placeholder="Site or project name" required></label><button class="primary" data-write>Create job</button></form><div class="jobs" id="jobList"></div><p id="storage" class="help"></p><button id="recover" data-write>Recover storage</button></section>
<section data-panel="setup" hidden><h2 id="setupTitle">Job setup</h2><p class="help">Coordinates are WGS84 grid coordinates. Select the actual source reference; no datum transformation or grid-to-ground scale is applied. Changing setup creates a new revision and preserves earlier points.</p><div class="banner">Zapopan starter values are prefilled for this prototype: WGS84 / UTM zone 13N, metres, ellipsoidal height, HA-609 antennas and a temporary base. Review the highlighted measurements and control information before saving; these defaults do not make a survey control-quality.</div>
<form id="config"><fieldset id="configuration"><div class="grid">
<label>Coordinate format<select name="crs"><option value="wgs84_utm">WGS84 / UTM</option><option value="wgs84_geographic">WGS84 latitude / longitude</option></select></label>
<label>Units<select name="units"><option value="m">Metres</option><option value="ft">International feet</option></select></label>
<label>UTM zone (1–60)<input name="zone" type="number" min="1" max="60" step="1" required></label><label>Hemisphere<select name="south" required><option value="">Select…</option><option value="false">Northern</option><option value="true">Southern</option></select></label>
<label>Reference frame<select name="frame"><option value="WGS84">WGS84 (no transformation)</option></select></label><label>Coordinate epoch (decimal year)<input name="epoch" type="number" min="2000" max="2100" step="any" required placeholder="e.g. 2026.69"><span class="help">Use the epoch documented for the control coordinates. The starter value is today’s approximate survey year and must be changed if your control uses another epoch.</span></label>
</div><label class="check"><input name="reference_confirmed" type="checkbox" required>I have confirmed that the correction source and control coordinates use WGS84 at the stated epoch.</label>
<div class="grid"><label>Height reference<select name="vertical" required><option value="">Select…</option><option value="ellipsoid">Ellipsoidal ground height</option><option value="constant_geoid">Local constant geoid separation</option></select><span class="help">Ellipsoidal is the safe starter choice. Select a constant geoid only when you have a locally validated separation and source.</span></label></div>
<div class="grid card" id="geoidFields"><label>Geoid / benchmark source<input name="geoid_name" maxlength="40" required></label><label>Separation N (metres; H = h − N)<input name="geoid_n" type="number" min="-150" max="150" step="any" required></label><label>Validity centre latitude (degrees)<input name="geoid_lat" type="number" min="-80" max="84" step="any" required></label><label>Validity centre longitude (degrees)<input name="geoid_lon" type="number" min="-180" max="180" step="any" required></label><label>Validity radius (metres; max 10 km)<input name="geoid_radius" type="number" min="1" max="10000" step="any" required></label><p class="help">Use only a locally validated constant separation. This is not an installed geoid grid; collection is blocked outside this area.</p></div>
<div class="card"><h3>Rover antenna</h3><div class="grid" id="roverAntenna"></div></div><div class="card"><h3>Base antenna</h3><div class="grid" id="baseAntenna"></div></div>
<p class="help">All antenna measurements are in metres. Slant measurement is converted using its horizontal radius. Add the signed vertical offset from the measurement mark to the receiver’s reported reference. Check the antenna documentation; a model name does not load a calibration.</p>
<label class="check"><input name="antenna_confirmed" type="checkbox" required>I checked both antenna reference points, offsets and measured heights.</label>
<div class="card"><h3>Base reference</h3><p class="help" id="referenceInfo">Waiting for reference coordinates…</p><p class="help">To change the Base receiver, open the Base instrument’s web address and pair there. This job checks the base coordinates received in RTCM before accepting a point. The Zapopan starter uses a temporary, unverified base for local testing; choose Known control only when you have surveyed control coordinates.</p><div class="grid"><label>Base / control name<input name="base_name" maxlength="40" required></label><label>RTCM station ID<input name="station" type="number" min="0" max="4095" step="1" required></label><label>Base coordinate source<select name="base_mode" required><option value="">Select…</option><option value="known">Known control</option><option value="temporary">Temporary / unverified</option></select></label></div>
<div class="grid" id="knownFields"><label>Control latitude (degrees)<input name="base_lat" type="number" min="-80" max="84" step="any" required></label><label>Control longitude (degrees)<input name="base_lon" type="number" min="-180" max="180" step="any" required></label><label>Control ground ellipsoidal height (m)<input name="base_ground_h" type="number" min="-1000" max="10000" step="any" required></label><label>Base reference tolerance (m)<input name="base_tolerance" type="number" min="0.001" max="1" step="any" value="0.02" required></label></div>
<label class="check" id="temporaryFields"><input name="temporary_confirmed" type="checkbox" required>I accept temporary base coordinates. Saved points will be marked as having unverified control.</label></div>
<div class="card"><h3>Point quality limits</h3><div class="grid"><label>Occupation duration (seconds)<input name="duration" type="number" min="1" max="600" step="1" value="5" required></label><label>Minimum distinct GNSS epochs<input name="min_samples" type="number" min="1" max="600" step="1" value="5" required></label><label>Maximum horizontal uncertainty (m)<input name="h_limit" type="number" min="0.001" max="1" step="any" value="0.03" required></label><label>Maximum vertical uncertainty (m)<input name="v_limit" type="number" min="0.001" max="2" step="any" value="0.05" required></label><label>Maximum correction age (milliseconds)<input name="correction_limit" type="number" min="500" max="10000" step="1" value="3000" required></label></div><p class="help">Every epoch must pass these limits and remain RTK FIXED. Uncertainty is reported by the receiver; it is not a guarantee of absolute accuracy.</p></div>
<label class="check"><input id="reviewConfig" type="checkbox" required>I reviewed this complete setup and want to save a new configuration revision.</label><button class="primary" data-write>Save job setup</button></fieldset></form></section>
<section data-panel="collect" hidden><h2 id="collectTitle">Collect a point</h2><div class="banner" id="quality">Open and configure a job.</div><form id="collect"><div class="grid"><label>Point ID<input name="point_id" maxlength="32" required placeholder="e.g. 1001"></label><label>Feature code<input name="code" maxlength="32" placeholder="e.g. BM"></label><label class="wide">Description<textarea name="description" maxlength="120" rows="2"></textarea></label></div><p class="help">Keep the pole still and level for the entire occupation. The point is saved only after the SD write and readback succeed.</p><button class="primary" id="start" data-write>Start occupation</button> <button type="button" id="cancel" data-write>Cancel occupation</button></form><div class="metric" id="progress">Ready for setup</div><p id="qualityStats" class="help"></p><div class="card" id="lastPoint" hidden><h3>Last committed point</h3><div class="details" id="pointDetails"></div></div></section>
<section data-panel="base" hidden><h2>Base receiver setup</h2><p class="help">This changes the Base receiver and saves its startup configuration. It interrupts corrections while the profile is applied. Fixed setup is confirmed only after the receiver profile and broadcast reference coordinates agree.</p><p id="baseLive" class="details"></p><form id="baseForm"><div class="grid"><label>Base mode<select name="mode"><option value="fixed">Fixed known coordinates</option><option value="temporary">Temporary survey-in</option></select></label></div><div id="baseFixed" class="grid"><label>Reference latitude (degrees, WGS84)<input name="latitude" type="number" min="-80" max="84" step="any" required></label><label>Reference longitude (degrees, WGS84)<input name="longitude" type="number" min="-180" max="180" step="any" required></label><label>Receiver-reference ellipsoidal height (m)<input name="reference_h" type="number" min="-1000" max="10000" step="any" required></label><p class="help">Enter the receiver reference height, including the measured base antenna height and its reference offset above the ground control mark. Do not enter orthometric ground elevation.</p></div><label class="check"><input name="confirm" type="checkbox" required>I checked the reference coordinates and antenna height, and can interrupt corrections now.</label><button class="primary" data-write>Apply and verify Base setup</button></form></section>
<p class="help">TopoRTK 0.6 · Instrument storage · Offline operation</p>
</main><script>
'use strict';
const $=id=>document.getElementById(id), cfg=$('config'), base=$('baseForm');
const uuid=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('');
const saved={get(k){try{return sessionStorage.getItem(k)}catch{return null}},set(k,v){try{v===null?sessionStorage.removeItem(k):sessionStorage.setItem(k,v)}catch{}}};
let token=saved.get('surveyToken')||'',client=saved.get('surveyClient')||uuid();saved.set('surveyClient',client);
let pending=null;try{pending=JSON.parse(saved.get('surveyPending')||'null')}catch{};
const zapopanDefaults={crs:'wgs84_utm',units:'m',zone:13,south:false,frame:'WGS84',epoch:2026.69,vertical:'ellipsoid',rover_model:'GNSS HA-609',rover_method:'vertical',base_model:'GNSS HA-609',base_method:'vertical',base_name:'Zapopan temporary base',base_mode:'temporary',duration:5,min_samples:5,h_limit:0.03,v_limit:0.05,correction_limit:3000,base_tolerance:0.02};
function applyStarterConfig(){for(const [name,value] of Object.entries(zapopanDefaults)){const x=cfg.elements.namedItem(name);if(x)x.value=String(value)}}
let state=null,controller=false,lastGood=0,sending=false,hydrated='',pendingSent=0,tab='jobs';
function message(s,bad=false){$('message').hidden=!s;$('message').textContent=s;$('message').classList.toggle('good',!bad)}
function switchTab(name){tab=name;document.querySelectorAll('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==name);document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',x.dataset.tab===name?'true':'false'))}
document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>switchTab(x.dataset.tab));
for(const prefix of ['rover','base']){$(prefix+'Antenna').innerHTML=`<label>Antenna model / reference<input name="${prefix}_model" maxlength="40" required></label><label>Measurement method<select name="${prefix}_method"><option value="vertical">Vertical</option><option value="slant">Slant</option></select></label><label>Measured height (m)<input name="${prefix}_height" type="number" min="0" max="10" step="any" required></label><label>Reference offset (m; signed)<input name="${prefix}_offset" type="number" min="-1" max="1" step="any" required></label><label>Slant horizontal radius (m; 0 if vertical)<input name="${prefix}_radius" type="number" min="0" max="1" step="any" required></label>`}
function conditional(id,show){$(id).hidden=!show;$(id).querySelectorAll('input,select').forEach(x=>x.disabled=!show)}
function conditions(){conditional('geoidFields',cfg.elements.vertical.value==='constant_geoid');conditional('knownFields',cfg.elements.base_mode.value==='known');conditional('temporaryFields',cfg.elements.base_mode.value==='temporary');conditional('baseFixed',base.elements.mode.value==='fixed')}
cfg.onchange=conditions;base.onchange=conditions;conditions();
function values(form){let out={};form.querySelectorAll('[name]').forEach(x=>{out[x.name]=x.type==='checkbox'?x.checked:x.type==='number'?(x.value===''?null:Number(x.value)):x.value});if('south'in out)out.south=out.south===''?null:out.south==='true';return out}
function active(){return state?.jobs?.find(j=>j.id===state.active_job)}
function fresh(){return state&&Date.now()-lastGood<4000}
function locked(){return !fresh()||!controller||sending||!state.storage_ready}
function controls(){const running=!!state?.collection?.active||state?.operation?.state==='applying';document.querySelectorAll('[data-write]').forEach(x=>x.disabled=locked()||running||!!pending);$('cancel').disabled=locked()||!state?.collection?.active||sending;$('retry').disabled=locked()||running||sending;$('recover').disabled=!fresh()||!controller||running||sending||!!pending;$('start').disabled=locked()||running||!!pending||!!state?.block_reason;$('retryPanel').hidden=!pending||Date.now()-pendingSent<4500;}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(3500)});const data=await r.json();if(!r.ok)throw Error(data.error||'Instrument request failed');return {data,r}}
async function submit(command,retry=false){if(!fresh()||!controller||sending)return;const request=retry?command:{...command,id:uuid()};pending=request;saved.set('surveyPending',JSON.stringify(request));pendingSent=Date.now();sending=true;controls();message('Sending request. Waiting for instrument confirmation…');try{await api('/api/v1/command',request)}catch(e){message(e.message+'. Check / retry this request to resolve its result.',true)}finally{sending=false;controls()}}
$('pair').onsubmit=async e=>{e.preventDefault();try{const {data}=await api('/api/v1/control',{pin:e.target.elements.pin.value,client});token=data.token;saved.set('surveyToken',token);e.target.reset();$('pairPanel').open=false;message('Control acquired.');await poll()}catch(e){message(e.message,true)}};
$('release').onclick=async()=>{try{await api('/api/v1/control/release',{})}catch{}token='';saved.set('surveyToken',null);controller=false;controls();$('controlState').textContent='View only · Pair to control'};
$('create').onsubmit=e=>{e.preventDefault();submit({op:'job.create',name:e.target.elements.name.value.trim()})};
cfg.onsubmit=e=>{e.preventDefault();const j=active();if(j)submit({op:'job.configure',job:j.id,revision:j.revision,confirm:true,config:values(cfg)})};
$('collect').onsubmit=e=>{e.preventDefault();const j=active();if(j)submit({op:'collect.start',job:j.id,revision:j.revision,...values(e.target)})};
$('cancel').onclick=()=>{if(state?.collection?.active){pending=null;submit({op:'collect.cancel'})}};
base.onsubmit=e=>{e.preventDefault();if(confirm('Apply these reviewed Base coordinates and interrupt corrections while they are verified?'))submit({op:'base.apply',...values(base)})};
$('retry').onclick=()=>pending&&submit(pending,true);$('recover').onclick=()=>submit({op:'storage.recover'});
function render(){const j=active(),isBase=state.role==='BASE';$('liveStatus').hidden=isBase;$('instrument').textContent='Unit '+state.unit+' · '+state.role+' · '+(j?'Job: '+j.name:'No active job');$('connection').textContent='Live · '+(state.gnss.profile_verified?'Receiver profile verified':'Receiver profile not verified');$('connection').classList.add('good');$('controlState').textContent=controller?'You control this instrument':'View only · Pair to control';
document.querySelectorAll('[data-tab]').forEach(x=>x.hidden=isBase?x.dataset.tab!=='base':x.dataset.tab==='base');if(isBase&&tab!=='base')switchTab('base');if(!isBase&&tab==='base')switchTab('jobs');
$('storage').textContent=state.storage_ready?`${state.jobs.length}/16 jobs · ${state.records_used}/${state.record_limit} journal records used. Limit: 512 unique saved commands.`:state.storage_error||'Storage unavailable.';
$('jobList').replaceChildren();for(const job of state.jobs){const row=document.createElement('div');row.className='job';const label=document.createElement('span');label.textContent=`${job.name}${job.id===state.active_job?' · OPEN':''} — ${job.points} points · ${job.revision?'setup r'+job.revision:'needs setup'}`;const b=document.createElement('button');b.textContent='Open';b.dataset.write='';b.onclick=()=>submit({op:'job.open',job:job.id});row.append(label,b);$('jobList').append(row)}
const key=(j?.id||'')+':'+(j?.revision||0);if(key!==hydrated){hydrated=key;cfg.reset();if(state.config)for(const [name,value]of Object.entries(state.config)){const x=cfg.elements.namedItem(name);if(x){if(x.type==='checkbox')x.checked=value===true;else x.value=String(value)}}else{applyStarterConfig();if(Number.isInteger(state.gnss.station)&&state.gnss.station>=0)cfg.elements.station.value=String(state.gnss.station)}$('reviewConfig').checked=false;conditions()}
$('configuration').disabled=!j; $('setupTitle').textContent=j?'Setup · '+j.name:'Open a job to configure it';$('collectTitle').textContent=j?'Collect · '+j.name:'Collect a point';
const g=state.gnss,ref=g.base_reference_available?`Station ${g.station} · ${g.base_latitude.toFixed(9)}°, ${g.base_longitude.toFixed(9)}° · receiver reference h ${g.base_reference_h.toFixed(4)} m`:'No fresh RTCM reference coordinates available.';$('referenceInfo').textContent=ref;$('baseLive').textContent=`Saved Base mode: ${g.base_mode} · revision ${g.base_revision}\n${g.base_mode==='fixed'?g.saved_base_latitude.toFixed(9)+'°, '+g.saved_base_longitude.toFixed(9)+'° · reference h '+g.saved_base_reference_h.toFixed(4)+' m\n':''}${ref}`;
$('quality').textContent=state.block_reason||'Ready · Every epoch must remain within the job limits.';$('quality').classList.toggle('good',!state.block_reason);const c=state.collection;$('progress').textContent=c.active?`${c.samples} epochs · ${(c.elapsed_ms/1000).toFixed(1)} s · ${c.point_id}`:'No occupation in progress';$('qualityStats').textContent=`${g.fixed?'RTK FIXED':'Not RTK FIXED'} · H σ ${Number(g.h_uncertainty_m).toFixed(3)} m · V σ ${Number(g.v_uncertainty_m).toFixed(3)} m`;
const p=state.last_point;$('lastPoint').hidden=!p;if(p)$('pointDetails').textContent=`${p.id}${p.code?' · '+p.code:''}\n${p.description||''}\n${p.easting!==undefined?'E '+p.easting.toFixed(3)+' · N '+p.northing.toFixed(3)+' '+p.configuration.units:p.latitude.toFixed(9)+'°, '+p.longitude.toFixed(9)+'°'}\nGround height ${p.height.toFixed(3)} ${p.configuration.units} · ${p.configuration.vertical}\n${p.samples} epochs · ${(p.duration_ms/1000).toFixed(1)} s · setup r${p.configuration_revision}\n${p.base_control_verified?'Known control matched':'TEMPORARY / UNVERIFIED CONTROL'}\n${p.utc_end||'UTC unavailable'}`;
const op=state.operation;if(pending&&op.id===pending.id){message(op.message,op.state==='rejected'||op.state==='interrupted');if(!['collecting','applying'].includes(op.state)){const kind=pending.op;pending=null;saved.set('surveyPending',null);if(op.state==='completed'&&kind==='job.create'){ $('create').reset();switchTab('setup')}if(op.state==='completed'&&kind==='job.configure')switchTab('collect')}}controls();}
let polling=false;async function poll(){if(polling)return;polling=true;const started=Date.now();try{const {data,r}=await api('/api/v1/survey');if(data.version!==1||!Array.isArray(data.jobs))throw Error('Unsupported instrument response');state=data;state.transport_ms=Date.now()-started;controller=r.headers.get('X-Controller')==='true';lastGood=Date.now();render()}catch(e){$('connection').textContent='Connection unavailable · Controls locked. Displayed values may be stale.';$('connection').classList.remove('good');lastGood=0;controls()}finally{polling=false}}
setInterval(()=>{if(!fresh()){controls();$('connection').textContent='Connection unavailable · Controls locked. Displayed values may be stale.';$('connection').classList.remove('good')}},500);poll();setInterval(poll,1000);
</script><script src="/survey-tools.js"></script></body></html>)SURVEY";
