#pragma once
static const char kSurveyTools[] = R"TOOLS(
'use strict';
const toolsNav=document.createElement('button');toolsNav.textContent='4 \u00b7 Points';toolsNav.dataset.tab='points';toolsNav.setAttribute('aria-selected','false');toolsNav.onclick=()=>switchTab('points');document.querySelector('nav').append(toolsNav);
const toolsPanel=document.createElement('section');toolsPanel.dataset.panel='points';toolsPanel.hidden=true;
toolsPanel.innerHTML=`<h2>Points & offline plan</h2><p class="help">Stored observations remain unchanged. Metadata edits and deletion/restoration are recorded with an audit reason. The plan shows the current setup revision only; the list retains all revisions.</p><div class="row"><label>Find ID or code<input id="pointSearch" type="search"></label><label class="check"><input id="showDeleted" type="checkbox">Show deleted</label><button id="reloadPoints" type="button">Reload</button></div><p id="pointsStatus" class="help"></p><canvas id="pointPlot" width="800" height="420" style="width:100%;height:300px;background:#101b22;border:1px solid #354852;border-radius:8px" aria-label="Offline north-up plan"></canvas><p class="help">North is up. Rover marker appears only with current quality-approved coordinates. All plotted distances use the current job's units.</p><div id="pointsList"></div><div id="pointInspector" class="card" hidden><h3 id="pointHeading"></h3><pre class="details" id="pointRecord" style="font:inherit"></pre><details><summary>Full observation and setup</summary><pre class="details" id="pointRaw" style="font-size:.8rem"></pre></details><form id="pointEdit"><div class="grid"><label>Code<input name="code" maxlength="32"></label><label>Description<input name="description" maxlength="120"></label><label class="wide">Note<input name="note" maxlength="240"></label><label class="wide">Audit reason<input name="reason" maxlength="120" required></label></div><label class="check"><input name="deleted" type="checkbox">Deleted (retained in audit and backup)</label><button data-write class="primary">Save metadata / deletion state</button></form></div>`;
document.querySelector('main').insertBefore(toolsPanel,document.querySelector('[data-panel=base]'));
let pointRows=[],pointsAt=-1,pointsJob='',pointsLoading=false,selectedPoint=null,pointEditCommand=null,inspectionTicket=0;
async function dataView(view,fields={}){const params=new URLSearchParams({view,job:active()?.id||'',...fields});const {data}=await api('/api/v1/data?'+params);if(data.error)throw Error(data.error);return data}
async function loadPoints(){if(pointsLoading||!fresh()||!active())return;pointsLoading=true;$('pointsStatus').textContent='Loading instrument records\u2026';try{const job=active().id;let rows=[],offset=0,at;do{const data=await dataView('points',{offset,deleted:true,...(at===undefined?{}:{at})});if(active()?.id!==job)return;rows.push(...data.points);at=data.at;offset=data.next}while(offset!==undefined);pointRows=rows;pointsAt=at;pointsJob=job;renderPoints()}catch(e){$('pointsStatus').textContent='Unable to load a consistent point list: '+e.message}finally{pointsLoading=false}}
function renderPoints(){const search=$('pointSearch').value.toLowerCase(),deleted=$('showDeleted').checked;const rows=pointRows.filter(p=>(deleted||!p.deleted)&&(!search||(p.id+' '+p.code).toLowerCase().includes(search)));$('pointsList').replaceChildren();$('pointsStatus').textContent=`${rows.length} shown / ${pointRows.length} records \u00b7 journal ${pointsAt}`;for(const p of rows){const row=document.createElement('div');row.className='job';const text=document.createElement('span');text.textContent=`${p.id} \u00b7 ${p.code||'No code'}${p.deleted?' \u00b7 DELETED':''} \u00b7 setup r${p.configuration_revision}`;const button=document.createElement('button');button.textContent='Review';button.onclick=()=>inspectPoint(p.id);row.append(text,button);$('pointsList').append(row)}drawPlan()}
function drawPlan(){const canvas=$('pointPlot'),ctx=canvas.getContext('2d'),w=canvas.clientWidth||800,h=300,dpr=window.devicePixelRatio||1;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.font='17px system-ui';ctx.fillStyle='#a6b8c4';ctx.fillText('N \u2191',20,26);let points=pointRows.filter(p=>!p.deleted&&p.configuration_revision===active()?.revision&&Number.isFinite(p.easting)&&Number.isFinite(p.northing));const rover=fresh()?state?.rover_position:null;const all=rover?[...points,rover]:points;if(!all.length){ctx.fillText('No projected points in the',25,75);ctx.fillText('current setup revision.',25,100);return}let loE=Math.min(...all.map(p=>p.easting)),hiE=Math.max(...all.map(p=>p.easting)),loN=Math.min(...all.map(p=>p.northing)),hiN=Math.max(...all.map(p=>p.northing));const scale=Math.min((w-100)/Math.max(hiE-loE,1),(h-100)/Math.max(hiN-loN,1));const xy=p=>[w/2+(p.easting-(loE+hiE)/2)*scale,h/2-(p.northing-(loN+hiN)/2)*scale];ctx.fillStyle='#a6ef65';for(const p of points){const [x,y]=xy(p);ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.fillText(p.id,x+7,y-7)}if(rover){const [x,y]=xy(rover);ctx.strokeStyle='#72c6ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#72c6ff';ctx.fillText('ROVER',x+14,y+7)}const bar=100/scale;ctx.strokeStyle='#a6b8c4';ctx.beginPath();ctx.moveTo(20,h-30);ctx.lineTo(120,h-30);ctx.stroke();ctx.fillStyle='#a6b8c4';ctx.fillText(bar.toFixed(2)+' '+(state?.config?.units||''),20,h-40)}
async function inspectPoint(id){const job=active()?.id,ticket=++inspectionTicket;try{const data=await dataView('point',{point:id,job});if(active()?.id!==job||ticket!==inspectionTicket)return;selectedPoint=data.point;const p=selectedPoint;$('pointInspector').hidden=false;$('pointHeading').textContent='Point '+p.id;$('pointRecord').textContent=(p.easting!==undefined?`E ${p.easting.toFixed(3)} \u00b7 N ${p.northing.toFixed(3)} ${p.configuration.units}`:`${p.latitude}\u00b0, ${p.longitude}\u00b0`)+`\nHeight ${p.height.toFixed(3)} ${p.configuration.units} \u00b7 ${p.configuration.vertical}\n${p.utc_end||'UTC unavailable'} \u00b7 ${p.samples||0} epochs\n${p.base_control_verified?'Known base control matched':'Unverified / derived control'} \u00b7 setup r${p.configuration_revision}\nMetadata revision ${p.edit_revision}${p.deleted?' \u00b7 DELETED':''}`;$('pointRaw').textContent=JSON.stringify(p,null,2);const form=$('pointEdit');for(const key of ['code','description','note'])form.elements[key].value=p[key]||'';form.elements.deleted.checked=p.deleted;form.elements.reason.value='';controls()}catch(e){message(e.message,true)}}
$('pointSearch').oninput=renderPoints;$('showDeleted').onchange=renderPoints;$('reloadPoints').onclick=loadPoints;
$('pointEdit').onsubmit=e=>{e.preventDefault();if(selectedPoint&&!pending){submit({op:'point.edit',job:active().id,point_id:selectedPoint.id,revision:selectedPoint.edit_revision,...values(e.target)});pointEditCommand=pending?.id}};
const surveyCoreRender=render;render=function(){surveyCoreRender();if(pointEditCommand&&state.operation.id===pointEditCommand&&state.operation.state==='completed'){pointEditCommand=null;if(selectedPoint)inspectPoint(selectedPoint.id)}if(pointsJob!==active()?.id){pointRows=[];pointsAt=-1;selectedPoint=null;$('pointInspector').hidden=true}if(tab==='points'&&pointsAt!==state.records_used)loadPoints();drawPlan()};
const surveyCoreTab=switchTab;switchTab=function(name){surveyCoreTab(name);if(name==='points')loadPoints()};
const surveyCoreControls=controls;controls=function(){surveyCoreControls();if(!fresh())drawPlan()};
const transfer=document.createElement('div');transfer.className='card';transfer.innerHTML=`<h3>Export & backup</h3><p class="help">CSV includes deleted points, setup revisions and original observation/quality JSON. The job backup preserves the complete journal and edit history with record checksums. Save both before fieldwork. Backup restore and CSV import are not available in this checkpoint.</p><div class="row"><button id="exportCSV" type="button">Export points CSV</button><button id="exportBackup" type="button">Download job backup</button></div><p id="exportStatus" role="status"></p>`;toolsPanel.append(transfer);
let exporting=false;
function downloadFile(name,type,body){const link=document.createElement('a'),url=URL.createObjectURL(new Blob([body],{type}));link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function csvCell(value){const s=value===undefined||value===null?'':String(value);return '"'+s.replaceAll('"','""')+'"'}
async function exportJob(backup){
 if(exporting||!fresh()||!active())return;exporting=true;$('exportCSV').disabled=$('exportBackup').disabled=true;$('exportStatus').textContent='Reading a consistent instrument snapshot...';
 const job=active().id,name=active().name.replace(/[^a-zA-Z0-9_-]/g,'_');
 try{let at,offset=0,rows=[],header;do{const data=await dataView(backup?'backup':'points',{job,offset,deleted:true,...(at===undefined?{}:{at})});header??=data;at=data.at;rows.push(...(backup?data.records:data.points));offset=data.next}while(offset!==undefined);
  if(backup){downloadFile(name+'-backup.json','application/json',JSON.stringify({format:header.format,version:header.version,job,name:header.name,revision:header.revision,at,records:rows},null,2));$('exportStatus').textContent=`Backup downloaded: ${rows.length} journal records. Retain this file unchanged.`}
  else {const keys=['id','code','description','note','deleted','edit_revision','configuration_revision','easting','northing','height','units','crs','vertical','latitude','longitude','utc_end','fix','samples','h_uncertainty_max_m','v_uncertainty_max_m','correction_age_max_ms','base_control_verified','comparison_purpose','reference_id','check_phase','delta_e','delta_n','delta_h','horizontal_residual','h_tolerance','v_tolerance','within_tolerance','independent_control','observation_json'];const lines=[keys.map(csvCell).join(',')];
   for(const row of rows){const data=await dataView('point',{job,point:row.id,at}),p=data.point;const c=p.comparison||{};const values={...p,comparison_purpose:c.purpose,reference_id:c.reference?.id,check_phase:c.phase,delta_e:c.delta_e,delta_n:c.delta_n,delta_h:c.delta_h,horizontal_residual:c.horizontal,h_tolerance:c.h_tolerance,v_tolerance:c.v_tolerance,within_tolerance:c.pass,independent_control:c.independent_control,units:p.configuration.units,crs:p.configuration.crs,vertical:p.configuration.vertical,observation_json:JSON.stringify(p)};
    // Prefix potentially executable spreadsheet text; exact original values remain in observation_json.
    for(const k of ['id','code','description','note','reference_id'])if(/^[=+@-]/.test(values[k]||''))values[k]="'"+values[k];lines.push(keys.map(k=>csvCell(values[k])).join(','));}
   downloadFile(name+'-points.csv','text/csv;charset=utf-8',lines.join('\r\n')+'\r\n');$('exportStatus').textContent=`CSV downloaded: ${rows.length} points, including deleted records. Coordinate units/reference are per row; exact metadata is in observation_json.`}
 }catch(e){$('exportStatus').textContent='Export failed; no complete file was produced: '+e.message}
 finally{exporting=false;$('exportCSV').disabled=$('exportBackup').disabled=false}
}
$('exportCSV').onclick=()=>exportJob(false);$('exportBackup').onclick=()=>exportJob(true);
const targetPanel=document.createElement('div');targetPanel.className='card';targetPanel.innerHTML=`<h3>Control & design targets</h3><p class="help">Enter a small set of documented reference coordinates for field checks and stakeout. Targets are immutable references, separate from measured points. Bulk file import belongs in the future phone/app workflow.</p><p id="targetReference" class="details"></p><details><summary>Add reference target</summary><form id="targetForm"><div class="grid"><label>Target ID<input name="id" maxlength="32" required></label><label>Use<select name="kind"><option value="control">Independent control</option><option value="design">Design / stakeout</option></select></label><label>Easting<input name="easting" type="number" step="any" required></label><label>Northing<input name="northing" type="number" step="any" required></label><label>Ground height<input name="height" type="number" step="any" required></label><label>Documented coordinate source<input name="source" maxlength="120" required placeholder="Control certificate / design revision"></label></div><label class="check"><input name="reference_confirmed" type="checkbox" required>I checked that the source uses exactly the reference, epoch, units and height model shown above.</label><label class="check"><input name="independent_source" type="checkbox">For control: these coordinates come from an independent source, not this rover's current fix or the same observation.</label><button data-write class="primary">Save reference target</button></form></details><p id="targetsStatus" class="help"></p><div id="targetsList"></div>`;toolsPanel.append(targetPanel);
const referenceKeys=['crs','frame','epoch','zone','south','units','vertical','geoid_name','geoid_n','geoid_lat','geoid_lon','geoid_radius'];
let targetRows=[],targetsAt=-1,targetContext='',targetsLoading=false;
async function loadTargets(){if(targetsLoading||!fresh()||!active())return;targetsLoading=true;const job=active().id;try{let rows=[],at,offset=0;do{const d=await dataView('targets',{job,offset,...(at===undefined?{}:{at})});if(active()?.id!==job)return;rows.push(...d.targets);at=d.at;offset=d.next}while(offset!==undefined);targetRows=rows;targetsAt=at;renderTargets()}catch(e){$('targetsStatus').textContent='Targets unavailable: '+e.message}finally{targetsLoading=false}}
function renderTargets(){const c=state?.config;$('targetReference').textContent=c?`${c.frame} / UTM ${c.zone}${c.south?'S':'N'} · epoch ${c.epoch} · ${c.units} · ${c.vertical}${c.vertical==='constant_geoid'?' / '+c.geoid_name+' / N='+c.geoid_n+' m':''} · setup r${active()?.revision}`:'Configure a UTM job before adding targets.';$('targetsStatus').textContent=`${targetRows.length} job targets · ${state?.targets_used||0}/64 instrument targets`;$('targetsList').replaceChildren();for(const t of targetRows){const row=document.createElement('div');row.className='details';row.textContent=`${t.id} · ${t.kind} · E ${t.easting.toFixed(3)} N ${t.northing.toFixed(3)} H ${t.height.toFixed(3)} ${t.reference.units}\n${t.source} · setup r${t.configuration_revision}${t.configuration_revision!==active()?.revision?' (previous setup; not selectable)':''}`;$('targetsList').append(row)}}
$('targetForm').onsubmit=e=>{e.preventDefault();if(!active()||!state.config||pending)return;const reference={};for(const key of referenceKeys)if(key in state.config)reference[key]=state.config[key];submit({op:'target.create',job:active().id,revision:active().revision,target:{...values(e.target),reference}})};
const targetCoreRender=render;render=function(){targetCoreRender();const key=(active()?.id||'')+':'+(active()?.revision||0);if(key!==targetContext){targetContext=key;targetsAt=-1;targetRows=[];$('targetForm').reset()}renderTargets();if(tab==='points'&&targetsAt!==state.records_used)loadTargets()};
const targetCoreTab=switchTab;switchTab=function(name){targetCoreTab(name);if(name==='points')loadTargets()};
const targetCoreControls=controls;controls=function(){targetCoreControls();if(!active()?.revision||state?.config?.crs!=='wgs84_utm')$('targetForm').querySelector('button').disabled=true};
const checkOptions=document.createElement('div');checkOptions.className='card';checkOptions.innerHTML=`<h3>Occupation purpose</h3><label>Method<select id="occupationPurpose"><option value="topo">Topo point</option><option value="check">Independent control check</option><option value="repeat">Repeat a measured point</option><option value="stake">Point stakeout / as-staked</option></select></label><div id="comparisonFields" hidden><p class="help">Save a new point ID for each occupation. Residuals are measured minus reference in the current UTM grid. A repeat tests repeatability; it does not establish independent control.</p><label id="controlTargetLabel"><span id="referenceTargetText">Independent control target</span><select id="checkTarget"></select></label><label id="repeatLabel" hidden>Measured reference point<select id="repeatPoint"></select></label><div class="grid"><label>Check phase<select id="checkPhase"><option value="start">Start of job</option><option value="intermediate">Intermediate</option><option value="end">End of job</option></select></label><label>Horizontal tolerance (job units)<input id="checkH" type="number" step="any" min="0.001"></label><label>Vertical tolerance (job units)<input id="checkV" type="number" step="any" min="0.001"></label></div><p id="comparisonUnits" class="help"></p></div>`;$('collect').prepend(checkOptions);
const comparisonResult=document.createElement('div');comparisonResult.id='comparisonResult';comparisonResult.className='banner';comparisonResult.hidden=true;$('lastPoint').append(comparisonResult);
function comparisonFields(){const purpose=$('occupationPurpose').value;$('comparisonFields').hidden=purpose==='topo';$('controlTargetLabel').hidden=purpose==='repeat';$('referenceTargetText').textContent=purpose==='stake'?'Stakeout target':'Independent control target';$('repeatLabel').hidden=purpose!=='repeat';for(const id of ['checkH','checkV'])$(id).required=purpose!=='topo';controls()}
function selectRows(id,rows){const select=$(id),old=select.value,signature=JSON.stringify(rows.map(r=>r.id));if(select.dataset.signature===signature)return;select.dataset.signature=signature;select.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='Select a reference...';select.append(empty);for(const row of rows){const option=document.createElement('option');option.value=row.id;option.textContent=row.id;select.append(option)}if(rows.some(r=>r.id===old))select.value=old}
function renderComparison(){if(state?.operation?.message?.includes('OUTSIDE tolerance'))message(state.operation.message,true);const rev=active()?.revision;selectRows('checkTarget',targetRows.filter(t=>t.configuration_revision===rev&&($('occupationPurpose').value==='stake'||t.kind==='control')));selectRows('repeatPoint',pointRows.filter(p=>!p.deleted&&p.configuration_revision===rev&&Number.isFinite(p.easting)));$('comparisonUnits').textContent=`Tolerances and residuals use ${state?.config?.units||'the configured units'}; no grid-to-ground conversion.`;const p=state?.last_point,c=p?.comparison;$('comparisonResult').hidden=!c;if(c){$('comparisonResult').textContent=`${c.purpose==='repeat'?'REPEATABILITY':c.purpose==='stake'?'AS-STAKED':'CONTROL CHECK'} · ${c.pass?'WITHIN TOLERANCE':'OUTSIDE TOLERANCE'}\nReference ${c.reference.id} · ${c.phase}\nΔE ${c.delta_e.toFixed(3)} · ΔN ${c.delta_n.toFixed(3)} · ΔH ${c.delta_h.toFixed(3)} ${c.units}\nHorizontal ${c.horizontal.toFixed(3)} / ${c.h_tolerance} · vertical ${Math.abs(c.delta_h).toFixed(3)} / ${c.v_tolerance} ${c.units}`;$('comparisonResult').classList.toggle('good',c.pass===true);$('comparisonResult').style.whiteSpace='pre-wrap'}}
$('occupationPurpose').onchange=()=>{comparisonFields();renderComparison();renderGuidance()};
$('collect').onsubmit=e=>{e.preventDefault();const j=active();if(!j)return;const purpose=$('occupationPurpose').value,command={op:'collect.start',job:j.id,revision:j.revision,...values(e.target)};if(purpose!=='topo')command.comparison={purpose,phase:$('checkPhase').value,h_tolerance:Number($('checkH').value),v_tolerance:Number($('checkV').value),...(purpose!=='repeat'?{target_id:$('checkTarget').value}:{reference_point:$('repeatPoint').value})};submit(command)};
const comparisonCoreRender=render;let comparisonContext='';render=function(){comparisonCoreRender();const key=(active()?.id||'')+':'+(active()?.revision||0);if(comparisonContext!==key){comparisonContext=key;$('occupationPurpose').value='topo';$('checkH').value='';$('checkV').value='';comparisonFields()}renderComparison();if(tab==='collect'){if(targetsAt!==state.records_used)loadTargets();if(pointsAt!==state.records_used)loadPoints()}};
const comparisonCoreTab=switchTab;switchTab=function(name){comparisonCoreTab(name);if(name==='collect'){loadTargets();loadPoints()}};

const guidance=document.createElement('div');guidance.id='stakeGuidance';guidance.className='banner';guidance.hidden=true;guidance.style.whiteSpace='pre-wrap';checkOptions.append(guidance);
function renderGuidance(){guidance.hidden=$('occupationPurpose').value!=='stake';if(guidance.hidden)return;const p=state?.rover_position,t=targetRows.find(t=>t.id===$('checkTarget').value&&t.configuration_revision===active()?.revision);guidance.classList.remove('good');if(!t||!p||!fresh()||Date.now()-lastGood+(state.transport_ms||0)+(p.age_ms||0)>1500){guidance.textContent='Guidance unavailable. Select a current target and wait for fresh quality-approved coordinates.';return}const e=t.easting-p.easting,n=t.northing-p.northing,h=t.height-p.height,d=Math.hypot(e,n),ht=Number($('checkH').value),vt=Number($('checkV').value),within=ht>0&&vt>0&&d<=ht&&Math.abs(h)<=vt;guidance.textContent=`${within?'WITHIN TOLERANCE':'APPROACH TARGET'} · ${t.id}
Move ${Math.abs(n).toFixed(3)} ${n>=0?'north':'south'} / ${Math.abs(e).toFixed(3)} ${e>=0?'east':'west'} ${t.reference.units}
Grid distance ${d.toFixed(3)} ${t.reference.units}
Design ${Math.abs(h).toFixed(3)} ${t.reference.units} ${h>=0?'higher (fill)':'lower (cut)'}
Keep the pole level. Save a new point ID for the as-staked occupation.`;guidance.classList.toggle('good',within)}
setInterval(renderGuidance,250);
)TOOLS";
