"""Embed the canonical web/ assets into flash-resident arrays and a route table.

Run by PlatformIO as a pre-build script (`extra_scripts = pre:tools/embed_web_assets.py`)
or standalone: `python tools/embed_web_assets.py <out-dir>`. The manifest
`web/assets.json` is the single source of truth: each entry names one source file,
its MIME type and the URLs that serve it. Output is one header in the
per-environment build directory (so parallel Unit A/B builds cannot collide) and is
rewritten only when its content changes, keeping incremental builds stable.

Missing files, duplicate URLs, duplicate sources and unsupported MIME types fail
the build instead of producing a half-embedded image.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

SUPPORTED_MIME = {
    "text/html; charset=utf-8",
    "application/javascript; charset=utf-8",
    "text/css; charset=utf-8",
}

try:  # PlatformIO pre-build hook; absent when run standalone as a script.
    Import("env")  # type: ignore[name-defined]
except Exception:  # noqa: BLE001 - any failure means "not under SCons"
    env = None  # type: ignore[assignment]


def project_dir() -> Path:
    """PlatformIO executes this file without __file__, so prefer $PROJECT_DIR."""
    if env is not None:
        return Path(env.subst("$PROJECT_DIR"))
    source = globals().get("__file__")
    return Path(source).resolve().parents[1] if source else Path.cwd().parent


def web_dir() -> Path:
    return project_dir() / "web"


def load_manifest() -> list[dict]:
    manifest = json.loads((web_dir() / "assets.json").read_text(encoding="utf-8"))
    assets = manifest.get("assets")
    if not isinstance(assets, list) or not assets:
        raise SystemExit("web/assets.json: 'assets' must be a non-empty list")
    seen_urls: dict[str, str] = {}
    seen_sources: set[str] = set()
    for entry in assets:
        source = entry.get("source")
        mime = entry.get("mime")
        urls = entry.get("urls")
        if not isinstance(source, str) or not source:
            raise SystemExit(f"web/assets.json: bad source in {entry!r}")
        if source in seen_sources:
            raise SystemExit(f"web/assets.json: duplicate source {source}")
        seen_sources.add(source)
        if mime not in SUPPORTED_MIME:
            raise SystemExit(f"web/assets.json: unsupported MIME {mime!r} for {source}")
        if not isinstance(urls, list) or not urls:
            raise SystemExit(f"web/assets.json: {source} has no urls")
        for url in urls:
            if not isinstance(url, str) or not url.startswith("/"):
                raise SystemExit(f"web/assets.json: bad url {url!r} for {source}")
            if url in seen_urls:
                raise SystemExit(f"web/assets.json: {url} served by both {seen_urls[url]} and {source}")
            seen_urls[url] = source
        if not (web_dir() / source).is_file():
            raise SystemExit(f"web/{source}: listed in the manifest but missing")
    return sorted(assets, key=lambda item: item["source"])


def c_identifier(source: str) -> str:
    return "kAsset_" + "".join(ch if ch.isalnum() else "_" for ch in source)


def c_literal(data: bytes) -> list[str]:
    # Fixed-width rows keep the generated header byte-for-byte reproducible.
    return ['  "' + "".join(f"\\x{byte:02x}" for byte in data[offset:offset + 16]) + '"'
            for offset in range(0, len(data), 16)]


def generate(output_dir: Path, assets: list[dict]) -> None:
    lines = [
        "// Generated by tools/embed_web_assets.py from web/assets.json. Do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "",
        "struct WebAsset {",
        "  const char *url;",
        "  const char *mime;",
        "  const char *data;",
        "  size_t length;",
        "};",
        "",
    ]
    routes = []
    for entry in assets:
        source = entry["source"]
        data = (web_dir() / source).read_bytes()
        identifier = c_identifier(source)
        lines.append(f"static const char {identifier}[] =")
        lines.extend(c_literal(data))
        lines.append(";")
        lines.append(f"static constexpr size_t {identifier}_length = {len(data)};")
        lines.append("")
        for url in entry["urls"]:
            routes.append((url, entry["mime"], identifier))
    lines.append(f"static constexpr size_t kWebAssetCount = {len(routes)};")
    lines.append("static const WebAsset kWebAssets[] = {")
    for url, mime, identifier in sorted(routes):
        lines.append(f'  {{"{url}", "{mime}", {identifier}, {identifier}_length}},')
    lines.append("};")
    lines.append("")

    target = output_dir / "web_assets.h"
    text = "\n".join(lines)
    if target.is_file() and target.read_text(encoding="utf-8") == text:
        return
    output_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8", newline="\n")
    total = sum(len((web_dir() / entry["source"]).read_bytes()) for entry in assets)
    print(f"embed_web_assets: {len(assets)} sources, {len(routes)} routes, {total} bytes -> {target}")


def main(argv: list[str]) -> None:
    if argv:
        generate(Path(argv[0]), load_manifest())
        return
    if env is None:
        raise SystemExit("usage: python tools/embed_web_assets.py <output-dir>")
    build_dir = env.subst("$BUILD_DIR") or str(project_dir() / ".pio" / "build" / env["PIOENV"])
    output_dir = Path(build_dir) / "web_assets"
    env.Append(CPPPATH=[str(output_dir)])
    generate(output_dir, load_manifest())


if globals().get("__file__"):
    # Standalone: python tools/embed_web_assets.py <output-dir>
    main(sys.argv[1:])
elif env is not None:
    # PlatformIO pre-build hook: SCons execs this file without __file__ or __main__.
    main([])
